import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ensureFeatures as upgraded} from '../src/trip-features.js';
const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
// Before, during and after the trip: the briefing, the wrap-up, stamps, the recap and the run-up.
test('the day in brief gathers the day number, stops, fixed times and a hotel move from the trip',async()=>{
 const {dayBriefing,briefingGreeting}=await import('../src/briefing-data.js');
 const state=upgraded(seed),kyoto=state.days.find(d=>d.date==='2026-09-24');
 const b=dayBriefing(state,kyoto.date);
 assert.equal(b.dayNumber,4);assert.equal(b.total,16);assert.ok(b.stops>0);
 assert.ok(b.fixed.some(f=>f.title==='Nozomi 33 to Kyoto'));
 assert.equal(b.moving,true);assert.ok(b.phrase?.en);
 assert.equal(dayBriefing(state,'2027-01-01'),null);
 assert.equal(dayBriefing(state,state.days.at(-1).date).last,true);
 assert.equal(briefingGreeting('2026-09-29','2026-09-29','08:10'),'Good morning');
 assert.equal(briefingGreeting('2026-09-29','2026-09-29','14:00'),'Today');
 assert.equal(briefingGreeting('2026-09-30','2026-09-29','08:00'),'Coming up');
});
test('tonight asks for stars, a photo vote and a memory, and counts what is left',async()=>{
 const {tonightShows,tonightFor}=await import('../src/tonight-data.js');
 assert.equal(tonightShows('2026-09-29','2026-09-29','16:59'),false);
 assert.equal(tonightShows('2026-09-29','2026-09-29','17:00'),true);
 assert.equal(tonightShows('2026-09-28','2026-09-29','09:00'),true,'an earlier day can still be wrapped');
 assert.equal(tonightShows('2026-09-30','2026-09-29','20:00'),false);
 const day='2026-09-22',state=upgraded(seed);
 const ids=state.steps.filter(s=>s.day===day).slice(0,4).map(s=>s.id);
 state.steps=state.steps.map(s=>ids.includes(s.id)?{...s,status:'done'}:s);
 let t=tonightFor(state,day,'Nate');
 assert.equal(t.tasks.rate,false);assert.equal(t.toRate.length,3);assert.equal(t.tasks.vote,true,'no photos, nothing to vote on');
 assert.equal(t.complete,false);
 state.stepReviews={[t.toRate[0].id]:{ratings:{Nate:4}}};
 assert.equal(tonightFor(state,day,'Nate').toRate.length,2);
 state.photos=[{id:'p1',day,by:'Nate',at:'2026-09-22T10:00:00Z'}];
 assert.equal(tonightFor(state,day,'Nate').tasks.vote,false);
 state.photoVotes={[day]:{Nate:'p1'}};state.journal={[day]:'A great day.'};
 assert.equal(tonightFor(state,day,'Nate').tasks.memory,false,'the diary is a parent’s; Nate needs a voice note');
 assert.equal(tonightFor(state,day,'Damien',true).tasks.memory,true);
 state.voiceNotes=[{id:'v',day,by:'Nate',at:'2026-09-22T11:00:00Z'}];
 state.stepReviews={...state.stepReviews,...Object.fromEntries(ids.slice(1,3).map(id=>[id,{ratings:{Nate:5}}]))};
 t=tonightFor(state,day,'Nate');assert.equal(t.complete,true);assert.equal(t.finished,3);
});
test('the stamp book is earned from what is ticked off, with milestones per person',async()=>{
 const {familyStamps,personalStamps,cityNames,MILESTONES}=await import('../src/stamp-data.js');
 const state=upgraded(seed);
 assert.deepEqual(cityNames(state).slice(0,4),['Tokyo','Kyoto','Osaka','Nara'],'Nara / Kyoto is two places');
 let f=familyStamps(state,'2026-09-20');
 assert.ok(f.every(c=>c.earned===0),'nothing before we land');
 const meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done',completedAt:'2026-09-22T01:00:00Z'}:s);
 f=familyStamps(state,'2026-09-20');
 const sight=f.find(c=>c.id==='sights').stamps.find(s=>s.id===meiji.id);
 assert.equal(sight.earned,true);assert.equal(sight.icon,'⛩️');assert.equal(sight.on,'2026-09-22');
 assert.equal(f.find(c=>c.id==='cities').stamps.find(s=>s.label==='Tokyo').earned,true,'a stop done in a city earns the city');
 assert.ok(f.find(c=>c.id==='trains').stamps.some(s=>s.label==='Nozomi 33 to Kyoto'&&s.icon==='🚅'));
 assert.ok(!f.find(c=>c.id==='rides').stamps.some(s=>/^Meet/.test(s.label)),'meeting a guide is not a ride');
 state.food={a:{tried:{Nate:'x'}},b:{tried:{Nate:'x',Boston:'x'}},c:{tried:{Nate:'x'}},d:{tried:{Nate:'x'}},e:{tried:{Nate:'x'}},f:{tried:{Boston:'x'}}};
 const food=personalStamps(state,'Nate').find(c=>c.id==='food');
 assert.equal(food.count,5);assert.deepEqual(food.stamps.map(s=>s.milestone),[1,5]);assert.equal(food.next,10);
 assert.equal(personalStamps(state,'Boston').find(c=>c.id==='food').count,2);
 assert.deepEqual(MILESTONES,[1,5,10,25,50]);
});
test('the leaderboard ranks everyone per board, shares a tie and gives no place for nought',async()=>{
 const {rankings,crowns}=await import('../src/leaderboard-data.js');
 const state=upgraded(seed);
 state.food={a:{tried:{Nate:'x',Boston:'x'}},b:{tried:{Nate:'x',Boston:'x'}},c:{tried:{Lauren:'x'}}};
 state.parkRides={r:{ridden:{Boston:'x'}}};
 const food=rankings(state).find(b=>b.id==='food');
 assert.deepEqual(food.rows.map(r=>[r.person,r.count,r.place]),[['Boston',2,1],['Nate',2,1],['Lauren',1,3],['Damien',0,null]]);
 assert.deepEqual(food.leaders,['Boston','Nate']);
 assert.deepEqual(rankings(state).find(b=>b.id==='photos').leaders,[],'nobody leads a board nobody has started');
 assert.deepEqual(crowns(state).slice(0,2),[{person:'Boston',crowns:2},{person:'Nate',crowns:1}]);
});
test('the trip story is counted out of what we kept, and leaves out a card with nothing to say',async()=>{
 const {recapStory}=await import('../src/recap-story.js');
 const state=upgraded(seed);
 let cards=recapStory(state,{today:'2026-09-29'});
 assert.deepEqual(cards.map(c=>c.kind),['title','numbers','places','end']);
 assert.equal(cards[0].sofar,true);assert.equal(cards[0].dayNumber,9);assert.equal(cards.at(-1).over,false);
 const meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done'}:s);
 state.stepReviews={[meiji.id]:{ratings:{Nate:5,Boston:4},thoughts:{Nate:{text:'The big gate!',at:'x'}}}};
 state.photos=[{id:'p1',day:'2026-09-22',by:'Boston',at:'2026-09-22T02:00:00Z'}];state.photoVotes={'2026-09-22':{Nate:'p1'}};
 state.food={tonkatsu:{tried:{Nate:'x'},ratings:{Nate:5}}};
 state.expenses=[{id:'e',day:'2026-09-22',yen:9800,category:'food',method:'card',paidBy:'Damien',title:'Lunch'}];
 cards=recapStory(state,{today:'2026-10-07',parent:true});
 assert.equal(cards[0].sofar,false);assert.equal(cards.at(-1).over,true);
 assert.equal(cards.find(c=>c.kind==='top').moments[0].average,4.5);
 assert.equal(cards.find(c=>c.kind==='photos').winners[0].photo.id,'p1');
 assert.equal(cards.find(c=>c.kind==='food').best[0].name,'Tonkatsu');
 const nate=cards.find(c=>c.kind==='person'&&c.person==='Nate');
 assert.equal(nate.favourite.title,meiji.title);assert.equal(nate.favourite.thought,'The big gate!');
 assert.equal(cards.find(c=>c.kind==='money').total,9800);
 assert.ok(!recapStory(state,{today:'2026-10-07'}).some(c=>c.kind==='money'),'spending is for parents');
});
test('replaying the trip draws what we did, or the plan before anything is ticked, and always has a place',async()=>{
 const {replayFrames,kmBetween}=await import('../src/memory-map.js');
 const state=upgraded(seed);
 let r=replayFrames(state);
 assert.equal(r.plan,true);assert.ok(r.frames.length>40);
 assert.ok(r.frames.every(f=>Number.isFinite(f.lat)&&Number.isFinite(f.lng)),'every frame has somewhere to be, even with no map coordinates');
 assert.equal(r.frames[0].dayNumber,1);assert.equal(r.frames.at(-1).dayNumber,16);
 const meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine'),nozomi=state.steps.find(s=>s.title==='Nozomi 33 to Kyoto');
 state.steps=state.steps.map(s=>[meiji.id,nozomi.id].includes(s.id)?{...s,status:'done'}:s);
 r=replayFrames(state);
 assert.equal(r.plan,false);assert.deepEqual(r.frames.map(f=>f.titles.at(-1)),[meiji.title,nozomi.title]);
 state.placeCoords={places:{},at:null,by:null};state.steps=state.steps.map(s=>s.id===meiji.id?{...s,pin:{lat:35.6764,lng:139.6993}}:s);
 assert.equal(replayFrames(state).frames[0].exact,true,'a pin is exact');
 assert.ok(Math.abs(kmBetween({lat:35.6812,lng:139.7671},{lat:34.9858,lng:135.7588})-364)<10,'Tokyo to Kyoto Station is about 364 km');
});
test('the photobook has a page for every day, led by the photo of the day',async()=>{
 const {photobookPages}=await import('../src/photobook-data.js');
 const state=upgraded(seed);
 let pages=photobookPages(state);
 assert.equal(pages.length,16);assert.equal(pages[0].hero,null,'a day with nothing kept still gets its page');
 const day='2026-09-22',meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.photos=[{id:'a',day,by:'Nate',at:'2026-09-22T01:00:00Z'},{id:'b',day,by:'Boston',at:'2026-09-22T02:00:00Z'}];
 state.photoVotes={[day]:{Nate:'a',Lauren:'a'}};
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done'}:s);
 state.stepReviews={[meiji.id]:{ratings:{Nate:5},thoughts:{Nate:{text:'So many trees',at:'x'}}}};
 state.journal={[day]:'Rain in the morning, sun by lunch.'};
 const p=photobookPages(state).find(x=>x.date===day);
 assert.equal(p.hero.item.id,'a');assert.equal(p.winner,true);assert.deepEqual(p.more.map(m=>m.item.id),['b']);
 assert.equal(p.best[0].title,meiji.title);assert.equal(p.quote.text,'So many trees');assert.equal(p.note,'Rain in the morning, sun by lunch.');
});
test('on this day brings a trip day back a month, and a year, on',async()=>{
 const {anniversary}=await import('../src/anniversary-data.js');
 const state=upgraded(seed);
 assert.equal(anniversary(state,'2026-09-29'),null,'not during the trip');
 assert.equal(anniversary(state,'2026-10-07'),null,'not the day after');
 assert.equal(anniversary(state,'2026-10-21').label,'One month ago today');
 assert.equal(anniversary(state,'2026-10-21').day,'2026-09-21');
 assert.equal(anniversary(state,'2027-01-23').label,'Four months ago today');
 assert.equal(anniversary(state,'2027-01-23').day,'2026-09-23');
 state.journal={'2026-09-23':'Sumo!'};
 const a=anniversary(state,'2027-09-23');
 assert.equal(a.label,'One year ago today');assert.equal(a.note,'Sumo!');
 assert.equal(anniversary(state,'2028-10-06').label,'Two years ago today');
 assert.equal(anniversary(state,'2027-10-15'),null,'a day that was not a trip day');
 assert.equal(anniversary(state,'2028-02-22'),null,'seventeen months is not an anniversary');
});
test('following along sends only the allow-list: days so far, photos, stars, words and the diary',async()=>{
 const {followView,followPhoto}=await import('../src/follow-data.js');
 const state=upgraded(seed),day='2026-09-22',meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done',pin:{lat:35.67,lng:139.69},bookingReference:'ABC123',phone:'03-1234-5678'}:s);
 state.stepReviews={[meiji.id]:{ratings:{Nate:5,Boston:4},thoughts:{Nate:{text:'Huge gate',at:'x'}}}};
 state.photos=[{id:'p1',day,by:'Nate',pathname:'photos/Nate/a.jpg',type:'image/jpeg',gps:{lat:35.6,lng:139.7},at:'2026-09-22T01:00:00Z'},{id:'p2',day:'2026-10-01',by:'Nate',pathname:'photos/Nate/b.jpg',type:'image/jpeg',at:'x'}];
 state.photoVotes={[day]:{Lauren:'p1'}};state.journal={[day]:'A day in the forest.'};
 state.expenses=[{id:'e',yen:5000}];state.contacts={Damien:'+61 400 000 000'};
 const v=followView(state,'2026-09-29');
 assert.equal(v.days.length,9,'only the days that have begun');assert.equal(v.days[0].number,9,'newest first');
 const d=v.days.find(x=>x.date===day);
 assert.deepEqual(d.photos,[{id:'p1',by:'Nate',best:true}]);
 assert.deepEqual(d.stops,[{id:meiji.id,title:meiji.title,stars:4.5,said:[{person:'Nate',text:'Huge gate'}]}]);
 assert.equal(d.diary,'A day in the forest.');
 const text=JSON.stringify(v);
 for(const secret of ['ABC123','03-1234-5678','+61','35.67','35.6','pathname','hotel','Hilton','Kanra','5000','Fantasy Springs'])assert.ok(!text.includes(secret),`${secret} must not reach a follower`);
 assert.equal(followPhoto(state,'p1','2026-09-29')?.id,'p1');
 assert.equal(followPhoto(state,'p2','2026-09-29'),null,'not a photo from a day still to come');
 assert.equal(followPhoto(state,(state.documents[0]||{}).id,'2026-09-29'),null,'never a ticket');
});
test('API: the follow-along link is a parent’s to make and stop, and a wrong or stopped key learns nothing',async()=>{
 const {createServer}=await import('node:http');const handler=(await import('../server/handler.mjs')).default;
 process.env.LOCAL_DEMO='1';delete process.env.VERCEL;
 const server=createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 try{
  const post=(path,data)=>fetch(base+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify(data)});
  assert.equal((await fetch(base+'/api/follow?key='+'a'.repeat(64))).status,403,'no link made yet');
  const {url}=await(await post('follow-link',{})).json();
  const key=new URL(url).searchParams.get('follow');assert.match(key,/^[a-f0-9]{64}$/);
  assert.equal((await(await post('follow-link',{})).json()).url,url,'asking again hands out the same link');
  const state=(await(await fetch(base+'/api/state')).json()).state;
  assert.equal('followKey' in state,false,'the key never travels with the trip');
  const r=await fetch(`${base}/api/follow?key=${key}`,{headers:{cookie:''}});assert.equal(r.status,200);
  const view=await r.json();assert.ok(Array.isArray(view.days));assert.equal('documents' in view,false);
  assert.equal((await fetch(`${base}/api/follow?key=${'b'.repeat(64)}`)).status,403);
  assert.equal((await fetch(`${base}/api/follow?key=nonsense`)).status,403);
  assert.equal((await fetch(`${base}/api/follow-photo?key=${key}&id=nope`)).status,404);
  await post('follow-link',{stop:true});
  assert.equal((await fetch(`${base}/api/follow?key=${key}`)).status,403,'a stopped link stops at once');
  const again=(await(await post('follow-link',{})).json()).url;assert.notEqual(again,url,'the next link is a different one');
 }finally{delete process.env.LOCAL_DEMO;await new Promise(r=>server.close(r));}
});
test('the run-up unlocks a family task at 100, 50, 30, 14 and 7 days, each counted from the trip',async()=>{
 const {runUp,prepMeasures,MILESTONES}=await import('../src/prep-data.js');
 const state=upgraded(seed);
 assert.equal(runUp(state,'2026-09-21'),null,'not once we have landed');
 let r=runUp(state,'2026-05-01');
 assert.equal(r.days,143);assert.equal(r.now,null);assert.equal(r.next.at,100);
 r=runUp(state,'2026-08-22');
 assert.equal(r.days,30);assert.equal(r.now.measure,'profiles','the oldest open task comes first');
 state.party={people:Object.fromEntries(state.members.map(n=>[n,{age:30}])),pace:'steady',budget:null,notes:''};
 r=runUp(state,'2026-08-22');assert.equal(r.milestones[0].complete,true);assert.equal(r.now.measure,'votes');
 const m=prepMeasures(state);
 assert.equal(m.phrases.total,20);assert.ok(m.tickets.total>0,'the fixed bookings are counted');
 assert.equal(m.packing.total,0);assert.equal(MILESTONES.map(x=>x.at).join(),'100,50,30,14,7');
 assert.equal(runUp(state,'2026-09-20').days,1);
});
