import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ensureFeatures as upgraded} from '../src/trip-features.js';
const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
// Before, during and after the trip: the briefing, the wrap-up, stamps, the recap and the run-up.
test('the day in brief gathers the day number, stops, fixed times and a hotel move from the trip',async()=>{
 const {dayBriefing,briefingGreeting}=await import('../src/briefing-data.js');
 const state=upgraded(seed),kyoto=state.days.find(d=>d.date==='2026-09-24');
 const b=dayBriefing(state,kyoto.date);
 assert.equal(b.dayNumber,4);assert.equal(b.total,16);assert.ok(b.stops>0);
 assert.ok(b.fixed.some(f=>f.title==='Nozomi 33 to Kyoto'));
 assert.equal(b.moving,true);assert.ok(b.phrase?.en);
 assert.equal(dayBriefing(state,'2027-01-01'),null);
 assert.equal(dayBriefing(state,state.days.at(-1).date).last,true);
 assert.equal(briefingGreeting('2026-09-29','2026-09-29','08:10'),'Good morning');
 assert.equal(briefingGreeting('2026-09-29','2026-09-29','14:00'),'Today');
 assert.equal(briefingGreeting('2026-09-30','2026-09-29','08:00'),'Coming up');
});
test('tonight asks for stars, a photo vote and a memory, and counts what is left',async()=>{
 const {tonightShows,tonightFor}=await import('../src/tonight-data.js');
 assert.equal(tonightShows('2026-09-29','2026-09-29','16:59'),false);
 assert.equal(tonightShows('2026-09-29','2026-09-29','17:00'),true);
 assert.equal(tonightShows('2026-09-28','2026-09-29','09:00'),true,'an earlier day can still be wrapped');
 assert.equal(tonightShows('2026-09-30','2026-09-29','20:00'),false);
 const day='2026-09-22',state=upgraded(seed);
 const ids=state.steps.filter(s=>s.day===day).slice(0,4).map(s=>s.id);
 state.steps=state.steps.map(s=>ids.includes(s.id)?{...s,status:'done'}:s);
 let t=tonightFor(state,day,'Nate');
 assert.equal(t.tasks.rate,false);assert.equal(t.toRate.length,3);assert.equal(t.tasks.vote,true,'no photos, nothing to vote on');
 assert.equal(t.complete,false);
 state.stepReviews={[t.toRate[0].id]:{ratings:{Nate:4}}};
 assert.equal(tonightFor(state,day,'Nate').toRate.length,2);
 state.photos=[{id:'p1',day,by:'Nate',at:'2026-09-22T10:00:00Z'}];
 assert.equal(tonightFor(state,day,'Nate').tasks.vote,false);
 state.photoVotes={[day]:{Nate:'p1'}};state.journal={[day]:'A great day.'};
 assert.equal(tonightFor(state,day,'Nate').tasks.memory,false,'the diary is a parent’s; Nate needs a voice note');
 assert.equal(tonightFor(state,day,'Damien',true).tasks.memory,true);
 state.voiceNotes=[{id:'v',day,by:'Nate',at:'2026-09-22T11:00:00Z'}];
 state.stepReviews={...state.stepReviews,...Object.fromEntries(ids.slice(1,3).map(id=>[id,{ratings:{Nate:5}}]))};
 t=tonightFor(state,day,'Nate');assert.equal(t.complete,true);assert.equal(t.finished,3);
});
test('the stamp book is earned from what is ticked off, with milestones per person',async()=>{
 const {familyStamps,personalStamps,cityNames,MILESTONES}=await import('../src/stamp-data.js');
 const state=upgraded(seed);
 assert.deepEqual(cityNames(state).slice(0,4),['Tokyo','Kyoto','Osaka','Nara'],'Nara / Kyoto is two places');
 let f=familyStamps(state,'2026-09-20');
 assert.ok(f.every(c=>c.earned===0),'nothing before we land');
 const meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done',completedAt:'2026-09-22T01:00:00Z'}:s);
 f=familyStamps(state,'2026-09-20');
 const sight=f.find(c=>c.id==='sights').stamps.find(s=>s.id===meiji.id);
 assert.equal(sight.earned,true);assert.equal(sight.icon,'⛩️');assert.equal(sight.on,'2026-09-22');
 assert.equal(f.find(c=>c.id==='cities').stamps.find(s=>s.label==='Tokyo').earned,true,'a stop done in a city earns the city');
 assert.ok(f.find(c=>c.id==='trains').stamps.some(s=>s.label==='Nozomi 33 to Kyoto'&&s.icon==='🚅'));
 assert.ok(!f.find(c=>c.id==='rides').stamps.some(s=>/^Meet/.test(s.label)),'meeting a guide is not a ride');
 state.food={a:{tried:{Nate:'x'}},b:{tried:{Nate:'x',Boston:'x'}},c:{tried:{Nate:'x'}},d:{tried:{Nate:'x'}},e:{tried:{Nate:'x'}},f:{tried:{Boston:'x'}}};
 const food=personalStamps(state,'Nate').find(c=>c.id==='food');
 assert.equal(food.count,5);assert.deepEqual(food.stamps.map(s=>s.milestone),[1,5]);assert.equal(food.next,10);
 assert.equal(personalStamps(state,'Boston').find(c=>c.id==='food').count,2);
 assert.deepEqual(MILESTONES,[1,5,10,25,50]);
});
test('the leaderboard ranks everyone per board, shares a tie and gives no place for nought',async()=>{
 const {rankings,crowns}=await import('../src/leaderboard-data.js');
 const state=upgraded(seed);
 state.food={a:{tried:{Nate:'x',Boston:'x'}},b:{tried:{Nate:'x',Boston:'x'}},c:{tried:{Lauren:'x'}}};
 state.parkRides={r:{ridden:{Boston:'x'}}};
 const food=rankings(state).find(b=>b.id==='food');
 assert.deepEqual(food.rows.map(r=>[r.person,r.count,r.place]),[['Boston',2,1],['Nate',2,1],['Lauren',1,3],['Damien',0,null]]);
 assert.deepEqual(food.leaders,['Boston','Nate']);
 assert.deepEqual(rankings(state).find(b=>b.id==='photos').leaders,[],'nobody leads a board nobody has started');
 assert.deepEqual(crowns(state).slice(0,2),[{person:'Boston',crowns:2},{person:'Nate',crowns:1}]);
});
test('the trip story is counted out of what we kept, and leaves out a card with nothing to say',async()=>{
 const {recapStory}=await import('../src/recap-story.js');
 const state=upgraded(seed);
 let cards=recapStory(state,{today:'2026-09-29'});
 assert.deepEqual(cards.map(c=>c.kind),['title','numbers','places','end']);
 assert.equal(cards[0].sofar,true);assert.equal(cards[0].dayNumber,9);assert.equal(cards.at(-1).over,false);
 const meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done'}:s);
 state.stepReviews={[meiji.id]:{ratings:{Nate:5,Boston:4},thoughts:{Nate:{text:'The big gate!',at:'x'}}}};
 state.photos=[{id:'p1',day:'2026-09-22',by:'Boston',at:'2026-09-22T02:00:00Z'}];state.photoVotes={'2026-09-22':{Nate:'p1'}};
 state.food={tonkatsu:{tried:{Nate:'x'},ratings:{Nate:5}}};
 state.expenses=[{id:'e',day:'2026-09-22',yen:9800,category:'food',method:'card',paidBy:'Damien',title:'Lunch'}];
 cards=recapStory(state,{today:'2026-10-07',parent:true});
 assert.equal(cards[0].sofar,false);assert.equal(cards.at(-1).over,true);
 assert.equal(cards.find(c=>c.kind==='top').moments[0].average,4.5);
 assert.equal(cards.find(c=>c.kind==='photos').winners[0].photo.id,'p1');
 assert.equal(cards.find(c=>c.kind==='food').best[0].name,'Tonkatsu');
 const nate=cards.find(c=>c.kind==='person'&&c.person==='Nate');
 assert.equal(nate.favourite.title,meiji.title);assert.equal(nate.favourite.thought,'The big gate!');
 assert.equal(cards.find(c=>c.kind==='money').total,9800);
 assert.ok(!recapStory(state,{today:'2026-10-07'}).some(c=>c.kind==='money'),'spending is for parents');
});
test('replaying the trip draws what we did, or the plan before anything is ticked, and always has a place',async()=>{
 const {replayFrames,kmBetween}=await import('../src/memory-map.js');
 const state=upgraded(seed);
 let r=replayFrames(state);
 assert.equal(r.plan,true);assert.ok(r.frames.length>40);
 assert.ok(r.frames.every(f=>Number.isFinite(f.lat)&&Number.isFinite(f.lng)),'every frame has somewhere to be, even with no map coordinates');
 assert.equal(r.frames[0].dayNumber,1);assert.equal(r.frames.at(-1).dayNumber,16);
 const meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine'),nozomi=state.steps.find(s=>s.title==='Nozomi 33 to Kyoto');
 state.steps=state.steps.map(s=>[meiji.id,nozomi.id].includes(s.id)?{...s,status:'done'}:s);
 r=replayFrames(state);
 assert.equal(r.plan,false);assert.deepEqual(r.frames.map(f=>f.titles.at(-1)),[meiji.title,nozomi.title]);
 state.placeCoords={places:{},at:null,by:null};state.steps=state.steps.map(s=>s.id===meiji.id?{...s,pin:{lat:35.6764,lng:139.6993}}:s);
 assert.equal(replayFrames(state).frames[0].exact,true,'a pin is exact');
 assert.ok(Math.abs(kmBetween({lat:35.6812,lng:139.7671},{lat:34.9858,lng:135.7588})-364)<10,'Tokyo to Kyoto Station is about 364 km');
});
test('the photobook has a page for every day, led by the photo of the day',async()=>{
 const {photobookPages}=await import('../src/photobook-data.js');
 const state=upgraded(seed);
 let pages=photobookPages(state);
 assert.equal(pages.length,16);assert.equal(pages[0].hero,null,'a day with nothing kept still gets its page');
 const day='2026-09-22',meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.photos=[{id:'a',day,by:'Nate',at:'2026-09-22T01:00:00Z'},{id:'b',day,by:'Boston',at:'2026-09-22T02:00:00Z'}];
 state.photoVotes={[day]:{Nate:'a',Lauren:'a'}};
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done'}:s);
 state.stepReviews={[meiji.id]:{ratings:{Nate:5},thoughts:{Nate:{text:'So many trees',at:'x'}}}};
 state.journal={[day]:'Rain in the morning, sun by lunch.'};
 const p=photobookPages(state).find(x=>x.date===day);
 assert.equal(p.hero.item.id,'a');assert.equal(p.winner,true);assert.deepEqual(p.more.map(m=>m.item.id),['b']);
 assert.equal(p.best[0].title,meiji.title);assert.equal(p.quote.text,'So many trees');assert.equal(p.note,'Rain in the morning, sun by lunch.');
});
test('on this day brings a trip day back a month, and a year, on',async()=>{
 const {anniversary}=await import('../src/anniversary-data.js');
 const state=upgraded(seed);
 assert.equal(anniversary(state,'2026-09-29'),null,'not during the trip');
 assert.equal(anniversary(state,'2026-10-07'),null,'not the day after');
 assert.equal(anniversary(state,'2026-10-21').label,'One month ago today');
 assert.equal(anniversary(state,'2026-10-21').day,'2026-09-21');
 assert.equal(anniversary(state,'2027-01-23').label,'Four months ago today');
 assert.equal(anniversary(state,'2027-01-23').day,'2026-09-23');
 state.journal={'2026-09-23':'Sumo!'};
 const a=anniversary(state,'2027-09-23');
 assert.equal(a.label,'One year ago today');assert.equal(a.note,'Sumo!');
 assert.equal(anniversary(state,'2028-10-06').label,'Two years ago today');
 assert.equal(anniversary(state,'2027-10-15'),null,'a day that was not a trip day');
 assert.equal(anniversary(state,'2028-02-22'),null,'seventeen months is not an anniversary');
});
test('following along sends only the allow-list: days so far, photos, stars, words and the diary',async()=>{
 const {followView,followPhoto}=await import('../src/follow-data.js');
 const state=upgraded(seed),day='2026-09-22',meiji=state.steps.find(s=>s.title==='Meiji Jingu forest and shrine');
 state.steps=state.steps.map(s=>s.id===meiji.id?{...s,status:'done',pin:{lat:35.67,lng:139.69},bookingReference:'ABC123',phone:'03-1234-5678'}:s);
 state.stepReviews={[meiji.id]:{ratings:{Nate:5,Boston:4},thoughts:{Nate:{text:'Huge gate',at:'x'}}}};
 state.photos=[{id:'p1',day,by:'Nate',pathname:'photos/Nate/a.jpg',type:'image/jpeg',gps:{lat:35.6,lng:139.7},at:'2026-09-22T01:00:00Z'},{id:'p2',day:'2026-10-01',by:'Nate',pathname:'photos/Nate/b.jpg',type:'image/jpeg',at:'x'}];
 state.photoVotes={[day]:{Lauren:'p1'}};state.journal={[day]:'A day in the forest.'};
 state.expenses=[{id:'e',yen:5000}];state.contacts={Damien:'+61 400 000 000'};
 const v=followView(state,'2026-09-29');
 assert.equal(v.days.length,9,'only the days that have begun');assert.equal(v.days[0].number,9,'newest first');
 const d=v.days.find(x=>x.date===day);
 assert.deepEqual(d.photos,[{id:'p1',by:'Nate',best:true}]);
 assert.deepEqual(d.stops,[{id:meiji.id,title:meiji.title,stars:4.5,said:[{person:'Nate',text:'Huge gate'}]}]);
 assert.equal(d.diary,'A day in the forest.');
 const text=JSON.stringify(v);
 for(const secret of ['ABC123','03-1234-5678','+61','35.67','35.6','pathname','hotel','Hilton','Kanra','5000','Fantasy Springs'])assert.ok(!text.includes(secret),`${secret} must not reach a follower`);
 assert.equal(followPhoto(state,'p1','2026-09-29')?.id,'p1');
 assert.equal(followPhoto(state,'p2','2026-09-29'),null,'not a photo from a day still to come');
 assert.equal(followPhoto(state,(state.documents[0]||{}).id,'2026-09-29'),null,'never a ticket');
});
test('API: the follow-along link is a parent’s to make and stop, and a wrong or stopped key learns nothing',async()=>{
 const {createServer}=await import('node:http');const handler=(await import('../server/handler.mjs')).default;
 process.env.LOCAL_DEMO='1';delete process.env.VERCEL;
 const server=createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 try{
  const post=(path,data)=>fetch(base+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify(data)});
  assert.equal((await fetch(base+'/api/follow?key='+'a'.repeat(64))).status,403,'no link made yet');
  const {url}=await(await post('follow-link',{})).json();
  const key=new URL(url).searchParams.get('follow');assert.match(key,/^[a-f0-9]{64}$/);
  assert.equal((await(await post('follow-link',{})).json()).url,url,'asking again hands out the same link');
  const state=(await(await fetch(base+'/api/state')).json()).state;
  assert.equal('followKey' in state,false,'the key never travels with the trip');
  const r=await fetch(`${base}/api/follow?key=${key}`,{headers:{cookie:''}});assert.equal(r.status,200);
  const view=await r.json();assert.ok(Array.isArray(view.days));assert.equal('documents' in view,false);
  assert.equal((await fetch(`${base}/api/follow?key=${'b'.repeat(64)}`)).status,403);
  assert.equal((await fetch(`${base}/api/follow?key=nonsense`)).status,403);
  assert.equal((await fetch(`${base}/api/follow-photo?key=${key}&id=nope`)).status,404);
  await post('follow-link',{stop:true});
  assert.equal((await fetch(`${base}/api/follow?key=${key}`)).status,403,'a stopped link stops at once');
  const again=(await(await post('follow-link',{})).json()).url;assert.notEqual(again,url,'the next link is a different one');
 }finally{delete process.env.LOCAL_DEMO;await new Promise(r=>server.close(r));}
});
test('the run-up unlocks a family task at 100, 50, 30, 14 and 7 days, each counted from the trip',async()=>{
 const {runUp,prepMeasures,MILESTONES}=await import('../src/prep-data.js');
 const state=upgraded(seed);
 assert.equal(runUp(state,'2026-09-21'),null,'not once we have landed');
 let r=runUp(state,'2026-05-01');
 assert.equal(r.days,143);assert.equal(r.now,null);assert.equal(r.next.at,100);
 r=runUp(state,'2026-08-22');
 assert.equal(r.days,30);assert.equal(r.now.measure,'profiles','the oldest open task comes first');
 state.party={people:Object.fromEntries(state.members.map(n=>[n,{age:30}])),pace:'steady',budget:null,notes:''};
 r=runUp(state,'2026-08-22');assert.equal(r.milestones[0].complete,true);assert.equal(r.now.measure,'votes');
 const m=prepMeasures(state);
 assert.equal(m.phrases.total,20);assert.ok(m.tickets.total>0,'the fixed bookings are counted');
 assert.equal(m.packing.total,0);assert.equal(MILESTONES.map(x=>x.at).join(),'100,50,30,14,7');
 assert.equal(runUp(state,'2026-09-20').days,1);
});
test('a little Japan each day counts back from the flight, and remembers what each person has learnt',async()=>{
 const {dailyJapan}=await import('../src/daily-japan-data.js');
 const state=upgraded(seed);
 assert.equal(dailyJapan(state,'2026-09-21','Nate'),null,'only before we fly');
 const eve=dailyJapan(state,'2026-09-20','Nate');
 assert.equal(eve.days,1);assert.equal(eve.phrase.id,'hello');assert.equal(eve.fact.id,'flight','the day before ends on the flight itself');
 assert.notEqual(dailyJapan(state,'2026-09-19','Nate').phrase.id,'hello','a new phrase each day');
 assert.equal(eve.phraseLearnt,false);
 state.phraseLog={Nate:{hello:'x'}};state.factLog={Nate:{flight:'x'}};
 const again=dailyJapan(state,'2026-09-20','Nate');
 assert.equal(again.phraseLearnt,true);assert.equal(again.factRead,true);
 assert.equal(dailyJapan(state,'2026-09-20','Boston').phraseLearnt,false,'each their own');
 const {applyOperation}=await import('../server/model.mjs');
 const next=applyOperation(state,{type:'phraseSeen',person:'Nate',day:null,phraseIds:['thanks']},{name:'Nate',role:'child'});
 assert.ok(next.phraseLog.Nate.thanks,'the run-up can log a phrase with no trip day');
});
test('sealed predictions are written before we fly, hidden from the others, and open once we are home',async()=>{
 const {applyOperation}=await import('../server/model.mjs');
 const {visibleTrip}=await import('../server/visibility.mjs');
 const {predictionPhase,visiblePredictions}=await import('../src/prediction-data.js');
 const {recapStory}=await import('../src/recap-story.js');
 assert.equal(predictionPhase(seed.days,'2026-09-20'),'open');assert.equal(predictionPhase(seed.days,'2026-09-21'),'sealed');assert.equal(predictionPhase(seed.days,'2026-10-07'),'revealed');
 const state=upgraded(seed);
 state.predictions={Nate:{fuji:{text:'Yes, from the train',at:'x'}},Boston:{food:{text:'Ramen',at:'x'},fuji:{text:'No',at:'x'}}};
 const seen=visiblePredictions(state,'Nate','2026-09-25');
 assert.deepEqual(seen.Nate,state.predictions.Nate,'your own you can read');
 assert.deepEqual(seen.Boston,{food:{sealed:true},fuji:{sealed:true}},'his are only a count');
 assert.ok(!JSON.stringify(visibleTrip(state,{name:'Nate',role:'child'},new Date('2026-09-25T03:00:00Z'))).includes('Ramen'),'not in what the server sends');
 assert.ok(JSON.stringify(visibleTrip(state,{name:'Nate',role:'child'},new Date('2026-10-07T03:00:00Z'))).includes('Ramen'),'opened once we are home');
 // The trip has begun by today's date, so the server refuses a change.
 assert.throws(()=>applyOperation(state,{type:'predictionSet',person:'Nate',id:'fuji',text:'Maybe'},{name:'Nate',role:'child'}),/sealed/);
 const cards=recapStory(state,{today:'2026-10-07'});
 const p=cards.find(c=>c.kind==='predictions');
 assert.deepEqual(p.asked.find(q=>q.id==='fuji').answers.map(a=>a.person),['Nate','Boston']);
 assert.ok(!recapStory(state,{today:'2026-09-29'}).some(c=>c.kind==='predictions'),'not before we are home');
});
test('ready to go weighs each of the five the same, and an empty list is not ready',async()=>{
 const {readiness}=await import('../src/prep-data.js');
 const state=upgraded(seed);
 let r=readiness(state);
 assert.equal(r.parts.length,5);assert.equal(r.parts.find(p=>p.id==='packing').share,0,'no packing list is not started');
 const before=r.percent;
 state.party={people:Object.fromEntries(state.members.map(n=>[n,{age:30}])),pace:'steady',budget:null,notes:''};
 r=readiness(state);assert.equal(r.percent,before+20,'four profiles are a fifth of ready, however few they are');
 state.packing={items:[{id:'a',title:'Hats',packedAt:'x'},{id:'b',title:'Socks',packedAt:null}],dismissed:{}};
 assert.equal(readiness(state).parts.find(p=>p.id==='packing').share,.5);
});
test('hunt picks: each of us picks the hunts to do, the boys their own, and everyone sees who picked what',async()=>{
 const {applyOperation}=await import('../server/model.mjs');
 const {huntPickers,pickedBy}=await import('../src/hunt-data.js');
 let state=upgraded(seed);
 state=applyOperation(state,{type:'huntPick',person:'Nate',hunt:'gachapon',picked:true},{name:'Nate',role:'child'});
 state=applyOperation(state,{type:'huntPick',person:'Boston',hunt:'gachapon',picked:true},{name:'Damien',role:'parent'});
 state=applyOperation(state,{type:'huntPick',person:'Nate',hunt:'ramen',picked:true},{name:'Nate',role:'child'});
 assert.deepEqual(huntPickers(state,'gachapon'),['Boston','Nate']);
 assert.deepEqual(pickedBy(state,'Nate').map(h=>h.id),['gachapon','ramen']);
 state=applyOperation(state,{type:'huntPick',person:'Nate',hunt:'ramen',picked:false},{name:'Nate',role:'child'});
 assert.deepEqual(pickedBy(state,'Nate').map(h=>h.id),['gachapon']);
 assert.throws(()=>applyOperation(state,{type:'huntPick',person:'Boston',hunt:'ramen',picked:true},{name:'Nate',role:'child'}),/own/);
 assert.throws(()=>applyOperation(state,{type:'huntPick',person:'Nate',hunt:'nope',picked:true},{name:'Nate',role:'child'}),/Choose a hunt/);
});
test('booking windows: when a booking opens, suggested from the plan, kept by a parent, and alerted in the calendar',async()=>{
 const {opensFor,suggestedWindows,windowState,upcomingWindows,findRule}=await import('../src/booking-window-data.js');
 const {applyOperation}=await import('../server/model.mjs');
 const {calendarFeed}=await import('../src/timing.js');
 // Japan time, turned into the instant it is everywhere else.
 assert.equal(opensFor(findRule('pokemon-cafe'),'2026-10-04'),'2026-09-03T09:00:00.000Z','31 days before, 18:00 in Japan');
 assert.equal(opensFor(findRule('ghibli'),'2026-03-05'),'2026-02-10T01:00:00.000Z','the 10th of the month before');
 assert.equal(opensFor(findRule('disney-dining'),'2026-03-31'),'2026-03-01T01:00:00.000Z','a month before a date February lacks is the 1st of March');
 assert.equal(opensFor(findRule('disney-dining'),'2026-09-30'),'2026-08-30T01:00:00.000Z');
 assert.equal(opensFor(findRule('disney-hotel'),'2026-10-31'),'2026-07-01T02:00:00.000Z','four months before at 11:00, as the official example says');
 let state=upgraded(seed);
 const s=suggestedWindows(state),titles=s.map(w=>w.title);
 assert.ok(titles.some(t=>/Chef Mickey dinner/.test(t)));assert.ok(titles.some(t=>/Nozomi 33/.test(t)));
 assert.ok(!titles.some(t=>/Buy breakfast|Hilton|Leave for/.test(t)),'only the meals that are bookable');
 assert.equal(s.filter(w=>w.ruleId==='disney-tickets').length,2,'one for each park day');
 const pick=s.find(w=>/Chef Mickey/.test(w.title));
 assert.throws(()=>applyOperation(state,{type:'bookingWindowAdd',...pick},{name:'Nate',role:'child'}),/parent/);
 state=applyOperation(state,{type:'bookingWindowAdd',...pick},{name:'Damien',role:'parent'});
 assert.ok(!suggestedWindows(state).some(w=>w.key===pick.key),'added, so no longer suggested');
 assert.throws(()=>applyOperation(state,{type:'bookingWindowAdd',...pick},{name:'Damien',role:'parent'}),/already/);
 const w=state.bookingWindows[0];
 assert.equal(windowState(w,new Date('2026-08-28T00:00:00Z')).kind,'soon');
 assert.equal(windowState(w,new Date('2026-08-29T01:00:00Z')).kind,'open');
 assert.equal(upcomingWindows(state,new Date('2026-08-20T00:00:00Z')).length,1,'inside the fortnight');
 assert.equal(upcomingWindows(state,new Date('2026-08-01T00:00:00Z')).length,0,'not a month out');
 assert.equal(upcomingWindows(state,new Date('2026-10-02T00:00:00Z')).length,0,'not once its day has gone');
 let ics=calendarFeed(state,'https://x');
 assert.match(ics,/SUMMARY:Booking opens: Tokyo Disney restaurant/);assert.match(ics,/DTSTART:20260829T010000Z/);assert.match(ics,/TRIGGER:-P1D/);
 state=applyOperation(state,{type:'bookingWindowBooked',id:w.id,booked:true},{name:'Lauren',role:'parent'});
 assert.equal(windowState(state.bookingWindows[0]).kind,'booked');
 assert.doesNotMatch(calendarFeed(state,'https://x'),/Booking opens/,'a booked one leaves the calendar');
 assert.throws(()=>applyOperation(state,{type:'bookingWindowAdd',title:'X',opensAt:'soon'},{name:'Damien',role:'parent'}),/when the booking opens/);
 assert.throws(()=>applyOperation(state,{type:'bookingWindowAdd',title:'X',opensAt:'2026-08-01T00:00:00Z',url:'http://insecure'},{name:'Damien',role:'parent'}),/https/);
});
test('the follow-along link is sent with a message written for family at home',async()=>{
 const src=await readFile(new URL('../src/Settings.jsx',import.meta.url),'utf8');
 assert.match(src,/navigator\.share\(\{title:'Follow our Japan trip',text\}\)/,'the phone’s own share sheet');
 assert.match(src,/Send to family at home/);
 const m=src.match(/export const followMessage=url=>`([^`]+)`/)[1];
 assert.match(m,/\$\{url\}/);assert.match(m,/No login needed/);assert.match(m,/don't pass it on/);
});
test('push: what falls due, who wants it, and nothing sent twice',async()=>{
 const {pushMoments,duePushes,wants,PUSH_LATE_LIMIT}=await import('../src/push-data.js');
 const {tick,tellChange,subscribe,resetDemoPush}=await import('../server/push.mjs');
 process.env.LOCAL_DEMO='1';delete process.env.VERCEL;resetDemoPush();
 try{
  const state=upgraded(seed),nozomi=state.steps.find(s=>s.title==='Nozomi 33 to Kyoto');
  const leave=pushMoments(state).find(m=>m.key.startsWith(`leave|${nozomi.id}`));
  assert.equal(new Date(leave.at).toISOString(),new Date(Date.parse('2026-09-24T12:30:00+09:00')-((nozomi.travelMinutes??20)+(nozomi.arrivalBuffer??15))*60000).toISOString(),'the same leave-by the calendar uses');
  assert.equal(new Date(pushMoments(state).find(m=>m.key==='morning|2026-09-24').at).toISOString(),'2026-09-23T22:30:00.000Z','7:30 in Japan');
  assert.deepEqual(duePushes(state,leave.at-1,leave.at).map(m=>m.key),[leave.key]);
  assert.deepEqual(duePushes(state,leave.at-1,leave.at+PUSH_LATE_LIMIT+1),[],'too late to be any use is not sent');
  assert.equal(wants({name:'Nate',prefs:{leave:false}},leave),false);
  assert.equal(wants({name:'Nate',prefs:{}},{...leave,to:['Damien']}),false,'not your booking');
  const sub=n=>({endpoint:`https://push.example/${n}`,keys:{p256dh:'k'.repeat(20),auth:'a'.repeat(10)}});
  await subscribe({name:'Nate'},sub('nate'),{});await subscribe({name:'Damien'},sub('damien'),{leave:false});
  const sent=[],send=async(s,p)=>{sent.push([s.endpoint,p.title]);};
  await tick(state,leave.at-10*60000,send);
  const out=await tick(state,leave.at+60000,send);
  assert.deepEqual(out.map(o=>o.key),[leave.key]);
  assert.ok(sent.some(([e,t])=>e.endsWith('/nate')&&/Nozomi 33/.test(t)));
  assert.ok(!sent.some(([e])=>e.endsWith('/damien')),'Damien turned leave-by off');
  assert.deepEqual(await tick(state,leave.at+120000,send),[],'nothing twice');
  sent.length=0;
  await tellChange({id:'a1',summary:'Dinner moved to 19:00',stepId:null},'Nate',send);
  assert.deepEqual(sent.map(([e])=>e),['https://push.example/damien'],'everyone but whoever changed it');
  await tellChange({id:'a1',summary:'again'},'Nate',send);assert.equal(sent.length,1,'a change is told once');
  const gone=async()=>{const e=new Error('Gone');e.statusCode=410;throw e;};
  await tellChange({id:'a2',summary:'x'},'Nate',gone);sent.length=0;
  await tellChange({id:'a3',summary:'y'},'Nate',send);assert.equal(sent.length,0,'a phone the push service says is gone is dropped');
 }finally{delete process.env.LOCAL_DEMO;resetDemoPush();}
});
test('API: the push tick needs the cron secret, and a phone cannot subscribe until the server has keys',async()=>{
 const {createServer}=await import('node:http');const handler=(await import('../server/handler.mjs')).default;
 process.env.LOCAL_DEMO='1';delete process.env.VERCEL;delete process.env.VAPID_PUBLIC_KEY;delete process.env.VAPID_PRIVATE_KEY;
 const server=createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 try{
  const post=(path,data)=>fetch(base+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify(data)});
  delete process.env.CRON_SECRET;
  assert.equal((await fetch(base+'/api/push-tick')).status,403,'no secret set, nobody gets in');
  process.env.CRON_SECRET='s'.repeat(32);
  assert.equal((await fetch(base+'/api/push-tick?key=wrong')).status,403);
  const r=await fetch(base+'/api/push-tick',{headers:{authorization:`Bearer ${'s'.repeat(32)}`}});assert.equal(r.status,200);
  assert.deepEqual(await r.json(),{ok:true,ready:false,sent:[]},'no keys, nothing sent');
  assert.equal((await(await fetch(base+'/api/config')).json()).push,false);
  assert.equal((await post('push-subscribe',{subscription:{}})).status,503);
 }finally{delete process.env.LOCAL_DEMO;delete process.env.CRON_SECRET;await new Promise(r=>server.close(r));}
});
test('tax-free: a flag on shopping and shortlist items, carried across, and a per-shop total against ¥5,000',async()=>{
 const {applyOperation}=await import('../server/model.mjs');
 const {taxFreeTally,TAX_FREE_MIN}=await import('../src/shopping-groups.js');
 const parent={name:'Damien',role:'parent'};
 let state=upgraded(seed);
 state=applyOperation(state,{type:'shoppingAdd',title:'Kit Kats',store:'Don Quijote, Shibuya',budget:3000,quantity:1,taxFree:true},parent);
 state=applyOperation(state,{type:'shoppingAdd',title:'Socks',store:'Don Quijote',budget:1500,quantity:1,taxFree:true},parent);
 state=applyOperation(state,{type:'shoppingAdd',title:'Postcard',store:'Don Quijote',budget:900,quantity:1},parent);
 assert.equal(state.shopping.at(-1).taxFree,false);
 let t=taxFreeTally(state.shopping);
 assert.equal(t.total,4500);assert.equal(t.reached,false);assert.equal(t.short,500);assert.equal(TAX_FREE_MIN,5000);
 state=applyOperation(state,{type:'shoppingEdit',id:state.shopping.at(-1).id,title:'Postcard',store:'Don Quijote',budget:900,quantity:1,taxFree:true},parent);
 t=taxFreeTally(state.shopping);assert.equal(t.reached,true);
 assert.equal(taxFreeTally([{taxFree:true,store:'',budget:9000}]),null,'no shop, no visit to count');
 state=applyOperation(state,{type:'shortlistAdd',title:'Kimono jacket',shop:'Nakamise',price:12000,taxFree:true},parent);
 const find=state.shortlist.at(-1);assert.equal(find.taxFree,true);
 state=applyOperation(state,{type:'shortlistStatus',id:find.id,status:'yes'},parent);
 state=applyOperation(state,{type:'shortlistShop',id:find.id},parent);
 assert.equal(state.shopping.at(-1).taxFree,true,'the flag comes across with it');
});
test('arrival paperwork: the declaration reminder shows in the 72 hours before the flight home',async()=>{
 const {declarationDue,VJW_STEPS,VISIT_JAPAN_WEB,TRAVEL_DECLARATION}=await import('../src/arrival-data.js');
 const {dayBriefing}=await import('../src/briefing-data.js');
 const state=upgraded(seed);
 assert.deepEqual(state.days.map(d=>declarationDue(state,d.date)).map((v,i)=>v?i+1:0).filter(Boolean),[14,15,16],'the last three days');
 assert.equal(dayBriefing(state,'2026-10-06').declaration,true);assert.equal(dayBriefing(state,'2026-09-29').declaration,false);
 assert.equal(VJW_STEPS.length,5);assert.match(VISIT_JAPAN_WEB,/^https:\/\/www\.vjw\.digital\.go\.jp\//);assert.match(TRAVEL_DECLARATION,/^https:\/\/www\.abf\.gov\.au\//);
});
test('the day map is drawn from positions the trip holds, needs no network, and keeps true distances',async()=>{
 const {dayMap,project,scaleBar}=await import('../src/day-map-data.js');
 const state=upgraded(seed),m=dayMap(state,'2026-09-24');
 assert.ok(m.marks.length>=2);assert.equal(m.legs.length,m.path.length-1);
 const order=m.path.flatMap(i=>m.marks[i].stops.map(s=>s.n));
 assert.ok(m.path.every((x,i)=>i===0||x!==m.path[i-1]),'no leg from a place to itself');
 assert.equal(new Set(order).size,m.marks.flatMap(x=>x.stops).length,'every stop is on the route');
 const back=dayMap(state,'2026-09-22');
 assert.ok(back.path.length>back.marks.length,'a place visited twice is gone back to');
 assert.ok(m.legs.some(l=>l.km>300),'Tokyo to Kyoto is the long leg');
 const p=project([{lat:35,lng:139},{lat:35,lng:139.01},{lat:35.01,lng:139}],300,300,0);
 const east=p.points[1].x-p.points[0].x,north=p.points[0].y-p.points[2].y;
 assert.ok(Math.abs(east/north-Math.cos(35*Math.PI/180))<.01,'a degree east is shorter than a degree north');
 assert.equal(scaleBar(.01,360).label,'500 m');assert.equal(scaleBar(1,360).label,'50 km');
 const src=await readFile(new URL('../src/DayMap.jsx',import.meta.url),'utf8');
 assert.doesNotMatch(src,/fetch\(|tile\.openstreetmap|https?:\/\//,'nothing in the map comes from the network');
});
test('apps to download: each app finds its days in the plan, and ones behind us are done',async()=>{
 const {SUGGESTED_APPS,APP_GROUPS,appDays,suggestedApps}=await import('../src/apps-data.js');
 const {PAGES,MORE_SECTIONS}=await import('../src/nav-data.js');
 const {PAGE_RULES}=await import('../src/spoken-rules.js');
 const state=upgraded(seed),byId=id=>SUGGESTED_APPS.find(a=>a.id===id);
 assert.deepEqual(appDays(state,byId('usj')),['2026-09-25']);
 assert.deepEqual(appDays(state,byId('smartex')),['2026-09-24','2026-09-29'],'both Nozomi days');
 assert.deepEqual(appDays(state,byId('disney')),['2026-09-29','2026-09-30','2026-10-01']);
 assert.deepEqual(appDays(state,byId('qantas')),['2026-09-21','2026-10-06'],'the two flight days');
 assert.equal(appDays(state,byId('maps')).length,16,'the rest are for the whole trip');
 const mid=Object.fromEntries(suggestedApps(state,'2026-09-28').map(a=>[a.id,a]));
 assert.equal(mid.usj.done,true);assert.equal(mid.disney.soon,true);assert.equal(mid.disney.next,'2026-09-29');
 assert.equal(mid.maps.soon,false,'whole-trip apps are never flagged');assert.equal(mid.qantas.soon,false);
 assert.equal(suggestedApps(state,'2026-09-01').filter(a=>a.done).length,0,'nothing is done before the trip');
 for(const a of SUGGESTED_APPS){assert.match(a.url,/^https:\/\/apps\.apple\.com\/au\/app\/[a-z-]+\/id\d+$/,a.id);assert.ok(APP_GROUPS.some(([g])=>g===a.group),a.id);assert.ok(a.why&&a.setup&&a.who,a.id);}
 assert.ok(PAGES.apps?.label&&PAGE_RULES.apps);assert.ok(MORE_SECTIONS.find(([t])=>t==='The plan')[1].includes('apps'));
});
