import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=async f=>readFile(new URL(`../src/${f}`,import.meta.url),'utf8');
// The UX review against hotel and event apps: each fix it led to is pinned here.
test('a pronunciation line wraps inside its card rather than being styled as the tiny label',async()=>{
 const css=await source('style.css');
 assert.doesNotMatch(css,/\.say-phonics span\{/,'only the first span is the SAY label');
 assert.match(css,/\.say-phonics>span:first-child\{font-size:\.75rem/);
 assert.match(css,/\.say-phonics>span\+span\{flex:1 1 auto;min-width:0\}/);
});
test('the weather list starts at today, with the days behind us folded above it',async()=>{
 const page=await source('WeatherPage.jsx');
 assert.match(page,/behind=state\.days\.filter\(d=>d\.date<today\)/);
 assert.match(page,/<summary>Earlier days \(\{earlier\.length\}\)<\/summary>/);
 assert.match(page,/open=\{earlier\.some\(d=>d\.date===open\)\|\|undefined\}/,'a past day asked for opens its fold');
 assert.match(page,/<details className="page-help"><summary>How this works<\/summary>/,'the explanation folds under the button');
 assert.match(page,/No forecast saved yet\./);
});
test('the phrase and fun fact of the day wait in a folding widget of their own instead of opening over Home',async()=>{
 const main=await source('main.jsx'),brief=await source('TodaysJapan.jsx');
 assert.doesNotMatch(main,/setModal\(\{type:'phrase',phrase:todaysPhrase,day:dayOnTrip\}\);\n \},/,'no effect opens the phrase');
 assert.doesNotMatch(main,/localStorage\.setItem\(`japan\.fact\.\$\{dayOnTrip\}`,'seen'\);setModal/,'no effect opens the fact');
 assert.match(main,/const openPhrase=\(\)=>todaysPhrase\?setModal\(\{type:'phrase'/);
 assert.match(main,/const openFact=\(\)=>todaysFact\?setModal\(\{type:'fact',day:dayOnTrip\}\)/);
 assert.match(main,/phrase=\{day===dayOnTrip&&settingOn\(settings,'dailyPhrase'\)\?\{item:phraseQueue\(visibleState,user\.name,dayOnTrip\)\[0\],open:openPhrase,fresh:!phraseDone\}:null\}/,'the row names the phrase its sheet opens on');
 assert.match(brief,/className="todays-japan-row" onClick=\{fact\.open\}/);
 assert.match(brief,/\{phrase\?\.fresh&&<em className="briefing-new">New<\/em>\}/);
 assert.match(brief,/<details className="todays-japan" open=\{open\} onToggle=/,'it folds, and the phone keeps the fold');
 assert.doesNotMatch(await source('Briefing.jsx'),/Today’s phrase/,'the day in brief no longer carries it');
});
test('no text is set below 12px, outside game boards and the drawn day map',async()=>{
 const exempt=['snake-cell','shogi-square','picross-cols','picross-rows','merge-tile','stable-cell','bingo-cell','.dm-','line-symbol','game-tile-stars','barrel-'];
 for(const f of ['style.css','stages.css','guide-theme.css']){
  const css=await source(f);
  for(const [,sel,body] of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)){
   if(exempt.some(e=>sel.includes(e)))continue;
   for(const [,v,u] of body.matchAll(/font-size:\s*(\.?\d*\.?\d+)(rem|px)(?![\w%])/g))
    assert.ok((u==='rem'?Number(v)*16:Number(v))>=12,`${f}: ${sel.trim().slice(-60)} is ${v}${u}`);
  }
 }
 // The printed guide is sized from one base: 16px on screen, 10pt on paper. Every size is a
 // multiple of it, never compounded, so its smallest on screen is 12px and on paper 7.5pt.
 const guide=await source('travel-guide.css');
 assert.match(guide,/\.travel-guide\{--tg-base:16px;/);
 for(const [,sel,body] of guide.matchAll(/([^{}]+)\{([^{}]*)\}/g)){
  if(sel.includes('.tg-map-'))continue;
  for(const [,size] of body.matchAll(/font-size:([^;]+)/g)){
   const k=size.match(/var\(--tg-base\) \* (\d*\.?\d+)\)/);
   assert.ok(k?Number(k[1])>=.75:/^(var\(--tg-base\)|10pt|\.9\d?rem)$/.test(size.trim()),`travel-guide.css: ${sel.trim().slice(-50)} is ${size}`);
  }
 }
});
test('dark mode: every colour in a stylesheet becomes a variable with a turned-over dark value',async()=>{
 const {themeCss,darkOf,parseColour}=await import('../scripts/dark-theme.mjs');
 const out=themeCss(':root{--ink:#16383b}.card{background:#fff;color:#16383b;box-shadow:0 4px 16px #24231b08;white-space:nowrap}.x:hover{border-color:rgba(0,0,0,.25)}/* white paper */');
 assert.match(out,/^:root\{--cffffff:#ffffff;--c16383b:#16383b;/,'the light values are exactly what was written');
 assert.match(out,/@media screen and \(prefers-color-scheme:dark\)\{:root\[data-theme=auto\]\{[^}]*color-scheme:dark\}\}/,'night is a choice: match the phone');
 assert.match(out,/@media screen\{:root\[data-theme=dark\]\{/,"printing stays on paper colours");
 assert.match(out,/--ink:#16383b/,'a named token keeps its value; its night value is set by hand under data-theme');
 assert.match(out,/background:var\(--cffffff\);color:var\(--c16383b\)/);
 assert.match(out,/white-space:nowrap/,'a property name is not a colour');
 assert.match(out,/\/\* white paper \*\//,'nor is a comment');
 const L=c=>{const [r,g,b]=parseColour(c);return (Math.max(r,g,b)+Math.min(r,g,b))/510;};
 assert.ok(L(darkOf('#fff'))<.15,'white paper turns dark');
 assert.ok(L(darkOf('#16383b'))>.7,'dark ink turns pale');
 assert.ok(L(darkOf('#24231b08'))<.1,'a shadow stays a shadow');
 assert.ok(L(darkOf('#da684f'))>=.55,'the accent keeps its strength');
 assert.equal(themeCss('.a{display:block}'),'.a{display:block}','a sheet with no colour is left as it was');
});
test('dark mode is built into every stylesheet, and the status bar follows the phone',async()=>{
 const vite=await readFile(new URL('../vite.config.js',import.meta.url),'utf8');
 const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
 assert.match(vite,/name:'dark-theme',enforce:'pre',transform\(code,id\)\{if\(\/\\\/src\\\/\[\^\/\]\+\\\.css\$\//);
 assert.match(html,/<meta name="theme-color" media="\(prefers-color-scheme: dark\)" content="#f4f3ef"\/>/,'light is the default on any phone until night is chosen');
 assert.doesNotMatch(html,/#102e32/);
});
test('screens lead with the tool, and a feature not switched on is left off rather than explained',async()=>{
 const yen=await source('Currency.jsx'),food=await source('FoodList.jsx'),main=await source('main.jsx');
 assert.ok(yen.indexOf('<section className="converter">')<yen.indexOf('<section className={`rate-card'),'the converter comes before the rate');
 assert.match(yen,/<details className="page-help"><summary>How this works<\/summary>Everything in Japan is priced in yen/);
 assert.match(food,/<strong>Allergies: always confirm with the restaurant, not with this list\.<\/strong>/);
 assert.match(main,/<div className="row wrap page-links"><button onClick=\{\(\)=>go\('allergy'\)\}>/);
 assert.doesNotMatch(main,/🥜 Allergy card/);
 for(const f of ['DocumentReader.jsx','FileTranslate.jsx','FoodList.jsx','PhotoDay.jsx','TicketTranslate.jsx'])
  assert.doesNotMatch(await source(f),/is not switched on for this trip yet\. Everything else|Photo tips are not switched on|Translating a file is not switched on/,f);
 assert.match(await source('DocumentReader.jsx'),/if\(!config\?\.documentReader\)return null;/);
 assert.match(main,/\{!parent&&<SpeakRules id=\{`page-\$\{tab\}`\}/,'the read-aloud button is on the boys\' phones');
 assert.match(await source('style.css'),/\.date-strip\{-webkit-mask-image:linear-gradient/,'the date strip fades at its edges so a cut-off day reads as more to scroll');
});
test('a stay is worked out from the plan: the run of nights, check-in and out, and the hotel from our map',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {staysOf,stayFor,cleanStay}=await import('../src/stay-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 const {locations}=JSON.parse(await readFile(new URL('../data/map-locations.json',import.meta.url)));
 const state={...ensureFeatures(seed),locations};
 assert.deepEqual(staysOf(state).map(s=>s.hotel),['1 Hotel Tokyo','Hotel Kanra Kyoto','Fantasy Springs Hotel','Hilton Tokyo']);
 const fsh=stayFor(state,'2026-09-30');
 assert.equal(fsh.from,'2026-09-29');assert.equal(fsh.to,'2026-10-01');
 assert.equal(fsh.night,2);assert.equal(fsh.total,2);assert.ok(fsh.leaving);
 assert.equal(fsh.checkIn,'15:00','from the plan’s check-in stop');
 assert.equal(fsh.checkOut,'07:30','from the plan’s check-out stop the morning after');
 assert.match(fsh.address,/Maihama/,'the address comes from our map');
 assert.ok(fsh.japanese,'and the Japanese name for the taxi card');
 const hilton=stayFor(state,'2026-10-05');
 assert.equal(hilton.checkOut,'09:00','the airport check-in is not the hotel’s');
 assert.equal(stayFor({...state,days:state.days.map(d=>({...d,hotel:''}))},'2026-09-30'),null);
 assert.deepEqual(cleanStay({reference:' ABC ',checkIn:'15:00'}).value,{reference:'ABC',checkIn:'15:00'});
 assert.match(cleanStay({checkOut:'11am'}).error,/24-hour clock/);
 assert.match(cleanStay({notes:'x'.repeat(601)}).error,/too long/);
});
test('a parent keeps a stay’s confirmation number and times for everyone, and nobody else can',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {applyOperation}=await import('../server/model.mjs');
 const {stayFor}=await import('../src/stay-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 let state=ensureFeatures(seed);
 assert.deepEqual(state.stays,{});
 state=applyOperation(state,{type:'stayEdit',hotel:'Hilton Tokyo',patch:{reference:'HT-2231',checkOut:'12:00',notes:'Late check-out agreed'}},{name:'Lauren',role:'parent'});
 assert.equal(state.stays['Hilton Tokyo'].reference,'HT-2231');assert.equal(state.stays['Hilton Tokyo'].by,'Lauren');
 const hilton=stayFor(state,'2026-10-03');
 assert.equal(hilton.reference,'HT-2231');assert.equal(hilton.checkOut,'12:00','an agreed time wins over the plan');
 assert.throws(()=>applyOperation(state,{type:'stayEdit',hotel:'Hilton Tokyo',patch:{reference:'x'}},{name:'Nate',role:'child'}),/parent/);
 assert.throws(()=>applyOperation(state,{type:'stayEdit',hotel:'Ritz',patch:{}},{name:'Lauren',role:'parent'}),/Unknown hotel/);
 assert.throws(()=>applyOperation(state,{type:'stayEdit',hotel:'Hilton Tokyo',patch:{checkIn:'3pm'}},{name:'Lauren',role:'parent'}),/24-hour/);
 const main=await source('main.jsx'),widgets=await source('home-widgets.js');
 assert.match(widgets,/stay:\{label:'Tonight’s stay'/);
 assert.match(main,/stay:<StayCard state=\{visibleState\} day=\{day\}/);
});
test('on the day we fly home the stay is the morning we check out, not another night',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {stayFor}=await import('../src/stay-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 const last=stayFor(ensureFeatures(seed),'2026-10-06');
 assert.ok(last.checkingOut);assert.equal(last.to,'2026-10-06');assert.equal(last.total,5);
});
test('the wallet leads with the next passes to scan, in the order we reach them',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {nextPasses}=await import('../src/wallet-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 const base=ensureFeatures(seed),day='2026-09-30',steps=base.steps.filter(s=>s.day===day&&s.time).sort((a,b)=>a.time.localeCompare(b.time));
 const doc=(id,step,extra={})=>({id,title:id,person:'Family',category:'ticket',stepIds:[step.id],...extra});
 const state={...base,documents:[doc('later',steps[4]),doc('first',steps[1]),doc('used',steps[0],{archivedAt:'2026-09-30T00:00:00Z'}),doc('page',steps[0],{parentDocumentId:'first'}),doc('yesterday',base.steps.find(s=>s.day==='2026-09-29'))]};
 assert.deepEqual(nextPasses(state,day).map(p=>p.doc.id),['first','later'],'in time order; used, attached pages and yesterday’s left out');
 const done={...state,steps:state.steps.map(s=>s.id===steps[1].id?{...s,status:'done'}:s)};
 assert.deepEqual(nextPasses(done,day).map(p=>p.doc.id),['later'],'a stop ticked off has used its pass');
 assert.equal(nextPasses(state,day,1).length,1);
 const main=await source('main.jsx'),nav=await source('nav-data.js');
 assert.match(main,/<h1>Wallet<\/h1><CodeReader [^>]*\/><CodePrompt .*?\/><NextPasses /,'the passes come first, under the line that says codes are being read');
 assert.match(main,/<summary>Search and filter all \{ticketList\(state,\{archived:false\}\)\.length\} bookings<\/summary>/);
 assert.match(nav,/tickets:\{label:'Wallet'/);
});
test('the build step leaves the hand-set night colours and the game boards alone, so nothing turns over twice',async()=>{
 const {themeCss}=await import('../scripts/dark-theme.mjs');
 const out=themeCss(':root[data-theme=dark]{--ink:#ece9df}@media (prefers-color-scheme:dark){:root[data-theme=auto]{--ink:#ece9df}}.merge-tile.filled{background:#fff}.picross-cell{background:#222}.note{color:#16383b}');
 assert.match(out,/:root\[data-theme=dark\]\{--ink:#ece9df\}/);
 assert.match(out,/:root\[data-theme=auto\]\{--ink:#ece9df\}/);
 assert.match(out,/\.merge-tile\.filled\{background:#fff\}/);assert.match(out,/\.picross-cell\{background:#222\}/);
 assert.match(out,/\.note\{color:var\(--c16383b\)\}/,'a one-off colour still follows');
 const {applyTheme,THEME_COLOUR}=await import('../src/theme.js');
 const metas=[{c:''},{c:''}].map(m=>({...m,setAttribute(k,v){this.c=v;}}));
 applyTheme('dark',{documentElement:{dataset:{}},querySelectorAll:()=>metas},false);
 assert.deepEqual(metas.map(m=>m.c),[THEME_COLOUR.dark,THEME_COLOUR.dark],'both of the page\'s bar colours follow the choice');
 assert.equal(THEME_COLOUR.light,'#f4f3ef','the bar is the page, not dark teal over cream');
});
test('ticket codes are read once, kept for everyone by a parent, and drawn fresh at the gate',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {applyOperation}=await import('../server/model.mjs');
 const {codesFor,toRead,cleanCode}=await import('../src/wallet-codes.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 const photo=(id,extra={})=>({id,title:id,person:'Family',type:'image/png',pathname:`tickets/${id}.png`,category:'ticket',...extra});
 let state={...ensureFeatures(seed),documents:[photo('park'),photo('nate',{parentDocumentId:'park',person:'Nate'}),photo('old',{archivedAt:'2026-09-01T00:00:00Z'}),photo('snap',{category:'memory'}),{id:'note',title:'Dinner',type:'note',person:'Family'}]};
 assert.deepEqual(toRead(state).map(d=>d.id),['park','nate'],'pictures on tickets in use; used tickets, memories and notes are not read');
 const lauren={name:'Lauren',role:'parent'};
 state=applyOperation(state,{type:'documentCode',id:'park',code:'TDR-1'},lauren);
 state=applyOperation(state,{type:'documentCode',id:'nate',code:'TDR-2'},lauren);
 assert.deepEqual(toRead(state),[],'each picture is read once');
 const park=state.documents.find(d=>d.id==='park');
 assert.deepEqual(codesFor(state,park).map(c=>[c.text,c.person]),[['TDR-1','Family'],['TDR-2','Nate']],'the ticket and its attached pages, whose each is');
 state=applyOperation(state,{type:'documentCode',id:'park',code:null},lauren);
 assert.deepEqual(codesFor(state,state.documents.find(d=>d.id==='park')).map(c=>c.text),['TDR-2'],'a picture with no code is kept as none');
 state=applyOperation(state,{type:'documentCode',id:'park',live:true,app:'Tokyo Disney Resort'},lauren);
 const live=state.documents.find(d=>d.id==='park');
 assert.equal(live.codeApp,'Tokyo Disney Resort');assert.deepEqual(codesFor(state,live),[],'a code that changes each time is never drawn as a copy');
 assert.throws(()=>applyOperation(state,{type:'documentCode',id:'nate',live:true},lauren),/ticket itself/);
 assert.throws(()=>applyOperation(state,{type:'documentCode',id:'park',code:'x'},{name:'Nate',role:'child'}));
 assert.match(cleanCode({code:'x'.repeat(3001)}).error,/not one the app can keep/);
 assert.match(cleanCode({live:true,app:'x'.repeat(61)}).error,/short/);
 const gate=await source('GateCode.jsx'),reader=await source('qr-reader.js'),dark=await readFile(new URL('../scripts/dark-theme.mjs',import.meta.url),'utf8');
 assert.match(reader,/await import\('jsqr'\)/,'the reader is fetched only when needed');
 assert.match(reader,/'b64:'\+btoa/,'a code that is not plain text is kept as its exact bytes');
 assert.match(gate,/navigator\.wakeLock\?\.request\('screen'\)/);
 assert.match(dark,/BOARDS=\/data-theme\|gate-code\|/,'the gate stays black on white at night');
});
test('PDF tickets are read too, and a file with several codes keeps them all in page order',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {applyOperation}=await import('../server/model.mjs');
 const {codesFor,toRead,cleanCode}=await import('../src/wallet-codes.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 let state={...ensureFeatures(seed),documents:[{id:'usj',title:'USJ e-ticket',person:'Family',type:'application/pdf',pathname:'tickets/usj.pdf',category:'ticket'},{id:'link',title:'Site',type:'link',url:'https://x.jp',person:'Family'}]};
 assert.deepEqual(toRead(state).map(d=>d.id),['usj'],'a PDF is read; a link has nothing to read');
 const lauren={name:'Lauren',role:'parent'};
 state=applyOperation(state,{type:'documentCode',id:'usj',code:['USJ-D','USJ-L','USJ-B','USJ-N']},lauren);
 const usj=state.documents.find(d=>d.id==='usj');
 assert.deepEqual(codesFor(state,usj).map(c=>[c.text,c.person]),[['USJ-D','Family · 1 of 4'],['USJ-L','Family · 2 of 4'],['USJ-B','Family · 3 of 4'],['USJ-N','Family · 4 of 4']]);
 assert.deepEqual(toRead(state),[]);
 assert.equal(cleanCode({code:['one']}).value.code,'one','a list of one is kept as the code');
 assert.equal(cleanCode({code:[]}).value.code,null,'an empty list is none');
 assert.match(cleanCode({code:['ok','']}).error,/not one the app can keep/);
 assert.match(cleanCode({code:Array(41).fill('x')}).error,/more codes/);
 const reader=await source('qr-reader.js');
 assert.match(reader,/await import\('pdfjs-dist\/legacy\/build\/pdf\.mjs'\)/,'the PDF reader is fetched only when a PDF is read');
 assert.match(reader,/for\(const n of \[2,3,4,5\]\)/,'the page is read again in sections, so several codes on one page are all found');
 assert.match(reader,/return qr\.createDataURL\(8,32\);/,'four modules of white round the drawn code, in pixels');
});
test('a code found is asked about before it goes in the Wallet, once for a whole booking',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {applyOperation}=await import('../server/model.mjs');
 const {codesFor,toRead,pendingCodes,isLink}=await import('../src/wallet-codes.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 const photo=(id,extra={})=>({id,title:id,person:'Family',type:'image/png',pathname:`t/${id}.png`,category:'ticket',...extra});
 let state={...ensureFeatures(seed),documents:[photo('usj'),photo('page2',{parentDocumentId:'usj',person:'Nate'}),photo('letter'),photo('blank')]};
 const lauren={name:'Lauren',role:'parent'},act=op=>{state=applyOperation(state,op,lauren);};
 act({type:'documentCode',id:'usj',found:['USJ-1']});act({type:'documentCode',id:'page2',found:['USJ-2']});
 act({type:'documentCode',id:'letter',found:['https://hotel.example/booking']});act({type:'documentCode',id:'blank',found:[]});
 assert.deepEqual(toRead(state),[],'found or not, nothing is read twice');
 assert.deepEqual(pendingCodes(state).map(p=>[p.doc.id,p.codes]),[['usj',['USJ-1','USJ-2']],['letter',['https://hotel.example/booking']]],'one question per booking; a file with no code asks nothing');
 const usj=()=>state.documents.find(d=>d.id==='usj');
 assert.deepEqual(codesFor(state,usj()),[],'nothing is in the Wallet until the answer is yes');
 assert.ok(isLink('https://hotel.example/booking'));assert.ok(!isLink('USJ-1'));
 act({type:'codesAnswer',id:'usj',add:true});
 assert.deepEqual(codesFor(state,usj()).map(c=>c.text),['USJ-1','USJ-2']);
 act({type:'codesAnswer',id:'letter',add:false});
 assert.deepEqual(pendingCodes(state),[]);
 assert.equal(state.documents.find(d=>d.id==='letter').code,null,'a no is kept, so it is never asked again');
 assert.throws(()=>applyOperation(state,{type:'codesAnswer',id:'usj',add:true},{name:'Nate',role:'child'}));
 assert.throws(()=>applyOperation(state,{type:'codesAnswer',id:'page2',add:true},lauren),/not found/,'answered on the booking, not a page of it');
 const gate=await source('GateCode.jsx'),widgets=await source('home-widgets.js');
 assert.match(gate,/mutate\(\{type:'documentCode',id:doc\.id,found:code\}\)/,'the reader only proposes');
 assert.match(widgets,/codes:\{label:'Codes found'/,'Home asks too');
});
test('a parent says whose each code is, and a code sent out of the app is recorded on the ticket',async()=>{
 const {ensureFeatures}=await import('../src/trip-features.js');
 const {applyOperation}=await import('../server/model.mjs');
 const {codesFor,startAt,codeKey}=await import('../src/wallet-codes.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url)));
 let state={...ensureFeatures(seed),documents:[{id:'usj',title:'USJ ×4',person:'Family',type:'application/pdf',pathname:'t/usj.pdf',category:'ticket',code:['D','L','B','N']}]};
 const lauren={name:'Lauren',role:'parent'},act=op=>{state=applyOperation(state,op,lauren);},usj=()=>state.documents.find(d=>d.id==='usj');
 assert.equal(startAt(codesFor(state,usj()),'Boston'),0,'with nobody named, every phone opens on the first');
 act({type:'codeOwner',id:'usj',key:codeKey('usj',2),person:'Boston'});
 const codes=codesFor(state,usj());
 assert.equal(codes[2].owner,'Boston');assert.equal(codes[2].who,'Boston');assert.equal(codes[0].who,'Family');
 assert.equal(startAt(codes,'Boston'),2,'Boston’s phone opens on his own code');
 assert.throws(()=>applyOperation(state,{type:'codeOwner',id:'usj',key:codeKey('usj',2),person:'Grandma'},lauren),/one of the family/);
 assert.throws(()=>applyOperation(state,{type:'codeOwner',id:'usj',key:codeKey('usj',9),person:'Nate'},lauren),/not on this ticket/);
 act({type:'codeOwner',id:'usj',key:codeKey('usj',2),person:''});
 assert.equal(codesFor(state,usj())[2].owner,null,'and can be unsaid');
 act({type:'codeSent',id:'usj',key:codeKey('usj',1)});
 const sent=codesFor(state,usj())[1].sent;
 assert.equal(sent.length,1);assert.equal(sent[0].by,'Lauren');assert.ok(sent[0].at);
 assert.throws(()=>applyOperation(state,{type:'codeSent',id:'usj',key:codeKey('usj',1)},{name:'Boston',role:'child'}),'sending a ticket is a parent’s call');
 const gate=await source('GateCode.jsx');
 assert.match(gate,/<strong>Sending it hands the ticket over\.<\/strong>/,'said plainly before it goes');
 assert.match(gate,/if\(navigator\.canShare\?\.\(\{files:\[file\]\}\)\)await navigator\.share/,'the phone’s share sheet');
 assert.match(gate,/if\(e\?\.name!=='AbortError'\)/,'a cancelled share is not recorded as sent');
 assert.match(gate,/const doc=state\.documents\.find\(d=>d\.id===opened\.id\)\|\|opened;/,'what changes on the ticket shows straight away');
});
// The review against apps outside travel (docs/ux-adjacent-apps.md): each mechanic borrowed is
// pinned here as it is built.
test('a report is a noticing with a kind on it: one tap, two hours on the others’ Home, then a memory',async()=>{
 const {reportFields,reportText,freshReports,REPORT_KINDS,REPORT_HOURS}=await import('../src/report-data.js');
 const {noticedFields}=await import('../src/noticed-data.js');
 const {applyOperation}=await import('../server/model.mjs');
 assert.equal(REPORT_HOURS,2);
 assert.deepEqual(REPORT_KINDS.map(k=>k.id),['queue','toilets','soldout','rain','tip']);
 assert.deepEqual(reportFields({kind:'queue',minutes:40}),{kind:'queue',minutes:40});
 assert.deepEqual(reportFields({kind:'toilets',minutes:40}),{kind:'toilets',minutes:null},'minutes only mean something on a queue');
 assert.equal(reportFields({kind:'police'}),null);
 assert.equal(reportText('queue',40),'Queue about 40 min');
 assert.equal(noticedFields({text:'x',report:{kind:'rain'}}).report.kind,'rain');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 const step=seed.steps.find(s=>s.day==='2026-09-30'),child={name:'Nate',role:'child'};
 const next=applyOperation(seed,{type:'noticedAdd',text:'Queue about 40 min',stepId:step.id,report:{kind:'queue',minutes:40}},child);
 const n=next.noticed.at(-1);
 assert.deepEqual(n.report,{kind:'queue',minutes:40});assert.equal(n.by,'Nate');
 assert.throws(()=>applyOperation(seed,{type:'noticedAdd',text:'x',stepId:step.id,report:{kind:'police'}},child),/not a report we know/);
 assert.throws(()=>applyOperation(seed,{type:'noticedAdd',text:'x',stepId:step.id,report:{kind:'queue',minutes:5000}},child),/not a report we know/);
 const at=new Date(n.at).getTime();
 assert.equal(freshReports(next,{day:'2026-09-30',now:new Date(at+60*60000)}).length,1,'shown for two hours');
 assert.equal(freshReports(next,{day:'2026-09-30',now:new Date(at+3*3600000)}).length,0,'then it is just a memory');
 assert.equal(freshReports(next,{day:'2026-10-01',now:new Date(at+60000)}).length,0,'on the day it was said');
 const main=await source('main.jsx'),widgets=await source('home-widgets.js'),links=await source('card-links.js');
 assert.match(main,/report:awarenessAllows\(visibleState,user\.name,'report'\)&&<button onClick=\{\(\)=>setModal\(\{type:'report',step:current\}\)\}/,'a Report button under the stop, for a phone whose awareness dial allows one');
 assert.match(main,/reports:<Reports state=\{visibleState\}/,'a Home widget of the last two hours');
 assert.match(widgets,/reports:\{label:'Reports from the family'/);
 assert.match(links,/report:\{label:'Report'/);
});
test('Check In: back at the hotel by 4:30, one open per person, arrived or amber when quiet past the time',async()=>{
 const {applyOperation}=await import('../server/model.mjs');
 const {liveCheckIns,checkInStatus,checkInDestinations,CHECKIN_QUIET_MIN,ARRIVED_SHOWN_MIN}=await import('../src/checkin-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 const child={name:'Nate',role:'child'},mum={name:'Lauren',role:'parent'},dad={name:'Damien',role:'parent'};
 const soon=new Date(Date.now()+3600000).toISOString();
 const dests=checkInDestinations(seed,'2026-10-02');
 assert.ok(dests.some(d=>d.hotel==='Hilton Tokyo'),'tonight’s hotel is a destination');
 assert.ok(dests.filter(d=>d.stepId).length>0,'and the day’s stops are');
 let s=applyOperation(seed,{type:'checkInStart',label:'Hilton Tokyo',hotel:'Hilton Tokyo',due:soon},child);
 const c=s.checkIns.at(-1);assert.equal(c.from,'Nate');assert.equal(c.arrivedAt,null);
 assert.equal(s.alerts[0].summary.slice(0,26),'Nate is heading to Hilton ','the others are told it started');
 assert.throws(()=>applyOperation(seed,{type:'checkInStart',label:'x',due:new Date(Date.now()-7200000).toISOString()},child),/next twelve hours/);
 assert.throws(()=>applyOperation(seed,{type:'checkInStart',label:'x',due:new Date(Date.now()+13*3600000).toISOString()},child),/next twelve hours/);
 s=applyOperation(s,{type:'checkInStart',label:'Tsukiji',due:soon},child);
 assert.equal(liveCheckIns(s).length,1,'a new one closes the last');assert.equal(liveCheckIns(s)[0].label,'Tsukiji');
 assert.throws(()=>applyOperation(s,{type:'checkInArrive',id:liveCheckIns(s)[0].id},{name:'Boston',role:'child'}),/whoever started it/);
 const arrived=applyOperation(s,{type:'checkInArrive',id:liveCheckIns(s)[0].id},mum);
 assert.ok(arrived.checkIns.at(-1).arrivedAt,'a parent can say they are back');
 assert.equal(arrived.alerts[0].summary,'Nate arrived at Tsukiji');
 assert.equal(liveCheckIns(arrived,new Date(Date.now()+(ARRIVED_SHOWN_MIN+1)*60000)).length,0,'an arrival leaves Home after half an hour');
 const gone=applyOperation(s,{type:'checkInCancel',id:liveCheckIns(s)[0].id},dad);assert.equal(liveCheckIns(gone).length,0);
 const due=new Date('2026-10-02T07:30:00Z'),ci={due:due.toISOString(),startedAt:'2026-10-02T06:30:00Z',arrivedAt:null};
 assert.equal(checkInStatus(ci,null,new Date(+due-60000)),'live');
 assert.equal(checkInStatus(ci,{at:new Date(+due).toISOString()},new Date(+due+5*60000)),'due','past the time but the phone still speaks');
 assert.equal(checkInStatus(ci,{at:new Date(+due).toISOString()},new Date(+due+(CHECKIN_QUIET_MIN+1)*60000)),'late');
 assert.equal(checkInStatus({...ci,arrivedAt:'x'},null,new Date()),'arrived');
 const main=await source('main.jsx'),home=await source('HomeFeatures.jsx');
 assert.match(home,/open\(\{type:'checkin'\}\)\}>Check in</,'started from the dashboard');
 assert.match(main,/checkin:<CheckInCard state=\{visibleState\}/);
});
test('big steps: a route as one thing per screen, a walk one screen and a ride two, read aloud and awake',async()=>{
 const {bigSteps}=await import('../src/BigSteps.jsx').catch(()=>null)||{};
 const route=await source('route-data.js'),big=await source('BigSteps.jsx'),card=await source('RouteCard.jsx');
 assert.match(big,/navigator\.wakeLock\?\.request\('screen'\)/,'the screen stays awake');
 assert.match(big,/move\(e\.clientX>window\.innerWidth\/2\?1:-1\)/,'the right half is next, the left is back');
 assert.match(big,/read\(`big-\$\{at\}`,s\.say,'en-AU'\)/,'each step can be read aloud');
 assert.match(big,/className="big-step-ja" lang="ja"/,'the station’s Japanese, large');
 assert.match(card,/<BigStepsButton onClick=\{\(\)=>setBig\(true\)\}\/>/,'opened from the route card');
 assert.match(card,/<BigSteps legs=\{legs\} step=\{step\} canTick=\{canTick&&ticks>0\}/);
 // The derivation is pure: a walk is one screen, a ride is board and get off.
 const src=big.replace(/^import .*$/mg,'').replace(/export default function BigSteps[\s\S]*$/,'');
 assert.match(src,/if\(leg\.mode==='walk'\)\{out\.push\(\{leg:k,kind:'walk'/);
 assert.match(src,/out\.push\(\{leg:k,kind:'board'/);assert.match(src,/out\.push\(\{leg:k,kind:'off'/);
 assert.match(route,/export function legStops/);
});
test('today’s puzzle: the same on every phone from the date, Wordle marks, a score against the day, a grid to share',async()=>{
 const {puzzleFor,katakanaPuzzle,markGuess,puzzleScore,shareGrid,stopPuzzle,pricePuzzle,daySeed}=await import('../src/puzzle-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 const a=puzzleFor(seed,'2026-10-02'),b=puzzleFor(seed,'2026-10-02');
 assert.deepEqual(a,b,'the same puzzle on every phone');
 assert.ok(daySeed('2026-10-02')>0);
 const k=katakanaPuzzle('2026-10-02',11);
 assert.ok(k.length>=3&&k.length<=5);assert.ok(k.keys.length<=16&&Array.from(k.word).every(c=>k.keys.includes(c)),'every kana of the word is on the keys');
 assert.ok(k.keys.every(c=>typeof c==='string'&&c.length===1)&&new Set(k.keys).size===k.keys.length,'sixteen real kana, no blanks and no repeats');
 assert.notEqual(katakanaPuzzle('2026-10-02',11).word,katakanaPuzzle('2026-10-03',12).word,'a new word each day');
 assert.deepEqual(markGuess('コーヒー','コーラー'),['hit','hit','miss','hit']);
 assert.deepEqual(markGuess('アイス','スイア'),['near','hit','near']);
 assert.deepEqual(markGuess('ケーキ','キキー'),['near','miss','near'],'a doubled kana counts once');
 assert.equal(puzzleScore(6,1,true),7);assert.equal(puzzleScore(6,6,true),2);assert.equal(puzzleScore(6,6,false),1);assert.equal(puzzleScore(3,3,true),2);
 assert.equal(stopPuzzle(seed,'2026-10-02'),null,'no photo on a stop yet, no stop puzzle');
 assert.equal(pricePuzzle(seed,'2026-10-02'),null,'nothing bought yet, no price puzzle');
 assert.equal(a.kind,'katakana','so today hands over to the katakana');
 const grid=shareGrid({dayNumber:12,tries:6},[{marks:['hit','near','miss']},{marks:['hit','hit','hit']}],true);
 assert.equal(grid,'Japan puzzle · Day 12 · 2/6\n🟩🟨⬜\n🟩🟩🟩');
 assert.doesNotMatch(grid,/[ァ-ヶ]/,'no letters in what is shared');
 const main=await source('main.jsx'),games=await source('Games.jsx');
 assert.match(main,/puzzle:<PuzzleLine state=\{visibleState\}/);assert.match(games,/\{id:'daily',title:'Today’s puzzle'/);
});
test('kudos from home: a clap, a heart or a wow from the follow-along link, one per follower per thing, never a word',async()=>{
 const {applyKudos,kudosFor,dayKudos,cleanKudosName,KUDOS}=await import('../src/kudos-data.js');
 const {followView}=await import('../src/follow-data.js');
 assert.deepEqual(KUDOS,['👏','❤️','😮']);
 assert.equal(cleanKudosName('  Grandma <script> '),'Grandma script'.replace(' script',' script'),'letters only');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 const step=seed.steps.find(s=>s.day==='2026-09-22');
 let s=applyKudos(seed,{target:'stop',id:step.id,emoji:'👏',name:'Grandma'});
 assert.deepEqual(kudosFor(s,'stop',step.id).counts,{'👏':1});
 s=applyKudos(s,{target:'stop',id:step.id,emoji:'❤️',name:'Grandma'});
 assert.deepEqual(kudosFor(s,'stop',step.id).counts,{'❤️':1},'a different one replaces');
 s=applyKudos(s,{target:'stop',id:step.id,emoji:'❤️',name:'Pop'});
 assert.equal(dayKudos(s,'2026-09-22').total,2);assert.deepEqual(dayKudos(s,'2026-09-22').givers,{Grandma:1,Pop:1});
 s=applyKudos(s,{target:'stop',id:step.id,emoji:'❤️',name:'Grandma'});
 assert.deepEqual(kudosFor(s,'stop',step.id).names,{Pop:'❤️'},'the same one again takes it back');
 assert.equal(applyKudos(seed,{target:'stop',id:step.id,emoji:'🍆',name:'Grandma'}),null,'only the three');
 assert.equal(applyKudos(seed,{target:'note',id:step.id,emoji:'👏',name:'Grandma'}),null,'only photos and stops');
 assert.equal(applyKudos(seed,{target:'stop',id:step.id,emoji:'👏',name:'   '}),null,'never nameless');
 const done={...s,steps:s.steps.map(x=>x.id===step.id?{...x,status:'done'}:x)};
 const view=followView(done,'2026-09-25');
 const row=view.days.flatMap(d=>d.stops).find(x=>x.id===step.id);
 assert.deepEqual(row.kudos,{Pop:'❤️'},'the follower sees who gave what');
 const handler=await readFile(new URL('../server/handler.mjs',import.meta.url),'utf8'),page=await source('FollowAlong.jsx');
 assert.match(handler,/route==='follow-react'&&post/);assert.match(handler,/hash\(key\)!==hash\(trip\.state\.followKey\)\)throw new AppError\('This follow-along link is not valid any more\.',403\);\n   if\(!applyKudos/,'the same key as the view, nothing more');
 assert.match(page,/localStorage\.getItem\('japan\.follow\.name'\)/,'a first name typed once');
 assert.doesNotMatch(page,/<textarea/,'still nothing to type into');
});
test('readiness at breakfast: one to five each, a parent for anyone, and under three the easier day is offered first',async()=>{
 const {applyOperation}=await import('../server/model.mjs');
 const {lowest,readinessOf,answered,LOW_READINESS,READINESS}=await import('../src/readiness-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 const nate={name:'Nate',role:'child'},mum={name:'Lauren',role:'parent'};
 assert.equal(READINESS.length,5);assert.equal(LOW_READINESS,3);
 let s=applyOperation(seed,{type:'readinessSet',day:'2026-10-02',person:'Nate',level:2},nate);
 assert.equal(readinessOf(s,'2026-10-02','Nate'),2);
 assert.throws(()=>applyOperation(seed,{type:'readinessSet',day:'2026-10-02',person:'Boston',level:4},nate),/a parent can say for the others/);
 assert.throws(()=>applyOperation(seed,{type:'readinessSet',day:'2026-10-02',person:'Nate',level:6},nate),/one to five/);
 s=applyOperation(s,{type:'readinessSet',day:'2026-10-02',person:'Boston',level:4},mum);
 assert.deepEqual(answered(s,'2026-10-02',seed.members),['Nate','Boston']);
 assert.deepEqual(lowest(s,'2026-10-02'),{person:'Nate',level:2});
 s=applyOperation(s,{type:'readinessSet',day:'2026-10-02',person:'Nate',level:3},mum);
 assert.equal(lowest(s,'2026-10-02'),null,'three is fine');
 const brief=await source('Briefing.jsx');
 assert.match(brief,/open\?\.\(\{type:'tired'\}\)/,'the easier day is one tap away');
 assert.match(brief,/mutate\(\{type:'readinessSet',day,person:p,level:r\.level\}\)/);
});
test('runway: at this pace the budget lasts, or runs out on a weekday; round-ups go to the keepsake fund',async()=>{
 const {runway,spendPace,biggestCategory}=await import('../src/runway-data.js');
 const {purse,keepsakeFund,roundUpOf}=await import('../src/trip-features.js');
 const {applyOperation}=await import('../server/model.mjs');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 assert.equal(runway(seed,'2026-10-02'),null,'nothing spent, nothing to say');
 const spend=(day,yen,category='food')=>({id:`${day}-${yen}`,title:'x',day,yen,category,paidBy:'Damien',method:'card',createdAt:day});
 const s={...seed,expenses:[spend('2026-09-28',30000),spend('2026-09-29',40000),spend('2026-09-30',50000,'activities'),spend('2026-10-01',60000)],party:{...(seed.party||{}),budget:40000}};
 assert.deepEqual(spendPace(s,'2026-10-02'),{yenPerDay:50000,days:3},'the last three days before today');
 assert.equal(biggestCategory(s,'2026-10-02').id,'food');
 const r=runway(s,'2026-10-02');
 assert.equal(r.daysLeft,5);assert.equal(r.tone,'warm');assert.match(r.text,/runs out on \w+day, 1 day before we fly home/);
 const fine=runway({...s,party:{budget:60000}},'2026-10-02');assert.equal(fine.tone,'calm');assert.match(fine.text,/lasts to the end/);
 const noBudget=runway({...s,party:{}},'2026-10-02');assert.match(noBudget.text,/rest of the trip comes to about ¥250,000/);
 // Round-ups: only a real price rounds, and the fund is what the purse gave up.
 assert.equal(roundUpOf({spent:340}),60);assert.equal(roundUpOf({spent:500}),0);assert.equal(roundUpOf({estimate:340}),0);
 const mum={name:'Lauren',role:'parent'},nate={name:'Nate',role:'child'};
 let t=applyOperation(seed,{type:'spendAdd',person:'Nate',title:'Gachapon',estimate:300},nate);
 const item=t.spending.items.at(-1);
 t=applyOperation(t,{type:'spendBought',id:item.id,done:true,spent:340},nate);
 assert.equal(keepsakeFund(t),0,'off until a parent turns it on');
 assert.throws(()=>applyOperation(t,{type:'spendRoundUp',person:'Nate',on:true},nate),/A parent/);
 t=applyOperation(t,{type:'spendRoundUp',person:'Nate',on:true},mum);
 assert.equal(keepsakeFund(t),60);assert.equal(purse(t,'Nate','2026-10-02').roundUps,60);
 assert.equal(purse(t,'Nate','2026-10-02').spent,400,'the purse gave up the round-up too');
});
test('the stage tracker: five stages to the booking that cannot move, tapped or reached by position, a move day its own five',async()=>{
 const {applyOperation}=await import('../server/model.mjs');
 const {stagesFor,stageReached,stageFromPosition,stageWords,STAGES_DAY,STAGES_MOVE}=await import('../src/stage-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 assert.deepEqual(STAGES_DAY.map(s=>s.label),['Packed','Left the hotel','On the train','Walking','At the gate']);
 assert.deepEqual(STAGES_MOVE.map(s=>s.label),['Packed','Checked out','Bags at the desk','On the Shinkansen','Checked in']);
 const disney=seed.steps.find(s=>s.day==='2026-10-01'),tokyo=seed.steps.find(s=>s.day==='2026-10-03');
 assert.equal(stagesFor(seed,disney),STAGES_MOVE,'the day we change hotel');assert.equal(stagesFor(seed,tokyo),STAGES_DAY);
 const nate={name:'Nate',role:'child'};
 const mine=seed.steps.find(s=>s.day==='2026-10-03'&&s.participants?.includes('Nate'));
 let s=applyOperation(seed,{type:'stageSet',id:mine.id,reached:3},nate);
 assert.equal(stageReached(s,mine.id),3);assert.equal(stageWords(STAGES_DAY,3),'On the train · next: walking');
 assert.throws(()=>applyOperation(seed,{type:'stageSet',id:mine.id,reached:6},nate),/nought to five/);
 const theirs=seed.steps.find(x=>x.day==='2026-10-03'&&x.participants?.length&&!x.participants.includes('Nate'));
 if(theirs)assert.throws(()=>applyOperation(seed,{type:'stageSet',id:theirs.id,reached:1},nate),/other family members/);
 assert.equal(stageFromPosition(seed,tokyo,null),null);
 const pinned={...tokyo,pin:{lat:35.68,lng:139.76}};
 assert.equal(stageFromPosition(seed,pinned,{lat:35.6801,lng:139.7601}),5,'at the gate');
 const main=await source('main.jsx'),home=await source('HomeFeatures.jsx');
 assert.match(main,/OFFLINE_OPS=\['status','legStatus','stageSet'/,'works with no signal');
 assert.match(home,/<StageTracker state=\{state\} step=\{fixed\}/,'under the next fixed booking');
});
test('halfway there: from the middle of the trip, the numbers so far on one square, counted out of the recap story',async()=>{
 const {halfwayDue,halfwayCard,halfwayLines}=await import('../src/halfway-data.js');
 const seed=JSON.parse(await readFile(new URL('../data/seed.json',import.meta.url),'utf8'));
 assert.equal(halfwayDue(seed,'2026-09-24'),false,'day four is not halfway');
 assert.equal(halfwayDue(seed,'2026-09-29'),true,'day nine of sixteen is');
 assert.equal(halfwayDue(seed,'2026-10-09'),false,'and home again is not');
 const done={...seed,steps:seed.steps.map(s=>s.day<'2026-09-30'?{...s,status:'done'}:s)};
 const card=halfwayCard(done,{today:'2026-09-30'});
 assert.equal(card.dayNumber,10);assert.equal(card.total,16);
 assert.ok(card.stats.some(([,,label])=>label==='stops done'));
 const lines=halfwayLines(card);
 assert.deepEqual(lines[0],['eyebrow','Day 10 of 16 · so far']);
 assert.equal(lines.at(-1)[0],'foot');
 assert.ok(lines.some(([k])=>k==='stat'));
 const {wrapLine}=await import('../src/halfway-data.js');
 assert.deepEqual(wrapLine(t=>t.length*10,'Tokyo Kyoto Osaka Nara',120,2),['Tokyo Kyoto','Osaka Nara']);
 assert.deepEqual(wrapLine(t=>t.length*10,'Tokyo Kyoto Osaka Nara Disney',120,2),['Tokyo Kyoto','Osaka…'],'at most two lines, the last ended with an ellipsis');
 const main=await source('main.jsx'),widgets=await source('home-widgets.js'),page=await source('HalfwayCard.jsx');
 assert.match(main,/halfway:<><HalfwayLine state=\{visibleState\}/);assert.match(widgets,/halfway:\{label:'Halfway there'/);
 assert.match(page,/navigator\.canShare\?\.\(\{files:\[file\]\}\)/,'the square goes to the share sheet as a picture');
});
test('Where we are: the family on a map, sharing for a while, and running late one tap from Home and the split',async()=>{
 const {SHARE_FOR,sharingUntil}=await import('../src/live-share.js');
 const {CHECKIN_HOURS}=await import('../src/memory-map.js');
 const {PAGES,MORE_SECTIONS}=await import('../src/nav-data.js');
 const {PAGE_RULES}=await import('../src/spoken-rules.js');
 const {HOME_WIDGETS}=await import('../src/home-widgets.js');
 const {PUSH_KIND_IDS}=await import('../src/push-data.js');
 assert.ok(SHARE_FOR.length&&SHARE_FOR.every(m=>m<=CHECKIN_HOURS*60),'never longer than the server keeps a position');
 assert.equal(sharingUntil(new Date(Date.now()-1000).toISOString()),null,'a share whose time is up has stopped');
 assert.ok(PAGES.whereabouts&&PAGE_RULES.whereabouts&&MORE_SECTIONS.find(([t])=>t==='Out and about')[1].includes('whereabouts'));
 assert.equal(HOME_WIDGETS.late.page,'whereabouts');assert.ok(PUSH_KIND_IDS.includes('late'));
 const main=await source('main.jsx'),home=await source('HomeFeatures.jsx'),split=await source('SplitDay.jsx'),page=await source('Whereabouts.jsx');
 assert.match(main,/const live=useLiveShare\(request,!!user\);/,'sharing keeps going whichever screen is open');
 assert.match(main,/modal\.type==='latemsg'&&<LateSheet/);assert.match(main,/late:<LateCards /);
 assert.match(home,/open\(\{type:'latemsg'\}\)\}>Tell the others we’re late/);
 assert.match(split,/laneOf\(split,user\.name\)&&day===japanDate\(now\)&&<button type="button" className="split-late"/);
 assert.match(page,/askPhoneWhereItIs\(5\)\);/);assert.match(page,/It is not sent to anyone/,'my own dot stays on this phone');
});
