// Washi's answer for every colour written straight into the stylesheets. The dark-theme step
// (dark-theme.mjs) already turns each literal colour into a custom property named after it
// (#16383b becomes var(--c16383b)); this writes src/house-colours.css, which points each of those
// at the Washi token nearest in role — paper, tint, hairline, ink, muted text, or the one colour
// of its hue family — so the colours nobody named still dress in the house look. It applies only
// in Washi and only off the boys' pages, which keep their colour; the printed guide is untouched.
// Transparent colours (shadows, scrims, washes) are left as written.
//
// Run it after adding colours to a stylesheet: node scripts/washi-colours.mjs
// The test in tests/corners.test.mjs fails while any colour is left out.
import {readFile,writeFile} from 'node:fs/promises';
import {themeCss,parseColour} from './dark-theme.mjs';
import {fileURLToPath} from 'node:url';
export const SHEETS=['style.css','stages.css','guide-theme.css'];
const src=f=>new URL(`../src/${f}`,import.meta.url);
// Every colour property the dark-theme step makes from a sheet, with the colour it stands for.
export function colourKeys(css){
 const head=themeCss(css).split('\n')[0];
 const light=/^:root\{([^}]*)\}/.exec(head)?.[1]||'';
 return light?light.split(';').map(d=>d.split(':')).filter(([k])=>k).map(([k,v])=>[k.slice(2),v]):[];
}
const hsl=([r,g,b])=>{
 r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2;
 if(max===min)return [0,0,l];
 const d=max-min,s=l>.5?d/(2-max-min):d/(max+min);
 const h=max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4;
 return [h*60,s,l];
};
const family=h=>h<20||h>=330?'red':h<50?'orange':h<70?'yellow':h<170?'green':h<260?'blue':'purple';
// The Washi token for one colour, by what a colour that light and that saturated does on a page.
export function washiFor(hex){
 const [r,g,b,a]=parseColour(hex);
 if(a<1)return null;
 const [h,s,l]=hsl([r,g,b]),f=family(h),grey=s<.14;
 if(l>=.965)return 'paper';
 if(l>=.88){if(grey)return 'tint';return {red:'blush',orange:'sand',yellow:'sand',green:'tint',blue:'tint',purple:'blush'}[f];}
 if(l>=.74){if(grey)return 'border';return {red:'blush-border',orange:'sand-border',yellow:'sand-border',green:'tint-border',blue:'tint-border',purple:'blush-border'}[f];}
 if(l<.24)return 'ink';
 if(grey)return l<.42?'ink':l<.6?'muted':'stone';
 if(l<.36)return {red:'danger',orange:'sand-ink',yellow:'gold-ink',green:'green-deep',blue:'accent',purple:'accent'}[f];
 return {red:'danger-bright',orange:'amber',yellow:'gold',green:'green',blue:'accent',purple:'accent'}[f];
}
export async function washiColours(){
 const seen=new Map();
 for(const f of SHEETS)for(const [k,v] of colourKeys(await readFile(src(f),'utf8')))if(!seen.has(k))seen.set(k,v);
 const pairs=[...seen].map(([k,v])=>[k,washiFor(v)]).filter(([,t])=>t).sort(([a],[b])=>a.localeCompare(b));
 return `/* Generated by scripts/washi-colours.mjs — do not edit by hand; run the script instead.
   Each colour written into style.css, stages.css and guide-theme.css, pointed at the Washi token
   nearest in role, in Washi and off the boys' pages only. */
:root[data-look=washi]:not(:has(main[data-kids])){${pairs.map(([k,t])=>`--${k}:var(--${t})`).join(';')}}
`;
}
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const css=await washiColours();
 await writeFile(src('house-colours.css'),css);
 console.log(`Wrote src/house-colours.css: ${(css.match(/--c/g)||[]).length} colours.`);
}
