import React,{useState} from 'react';
import {BOYS} from './trip-features.js';
import {japanClock,japanDate} from './timing.js';
export const dayLabel=d=>d?new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',weekday:'short',timeZone:'Asia/Tokyo'}).format(new Date(d+'T12:00:00+09:00')):'Whole trip';
export function DaySelect({state,value,onChange,name,allowAll=false}){return <select name={name} value={value} onChange={onChange}><option value="">{allowAll?'Whole trip':'Unscheduled'}</option>{state.days.map(d=><option key={d.date} value={d.date}>{dayLabel(d.date)} · {d.city}</option>)}</select>;}
export function Challenges({state,user,day,mutate,busy,initialId}){
 const initial=state.challenges.find(c=>c.id===initialId);
 const [scope,setScope]=useState(initial&&!initial.day?'overall':'daily'),[date,setDate]=useState(initial?.day||day),[boy,setBoy]=useState(initial?.participants[0]||(BOYS.includes(user.name)?user.name:'Nate')),[edit,setEdit]=useState(null);
 const parent=user.role==='parent',list=state.challenges.filter(c=>(scope==='daily'?c.day===date:c.day===null)&&c.participants.includes(boy)),done=list.filter(c=>c.completions[boy]).length;
 async function save(e){e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({type:edit?.id?'challengeEdit':'challengeAdd',id:edit?.id,title:f.get('title'),notes:f.get('notes'),day:f.get('day')||null,participants:f.getAll('participants')}))setEdit(null);}
 return <><p className="eyebrow">CURIOUS MINDS, BIG ADVENTURES</p><h1>Japan explorers</h1><p>Daily missions and whole-trip quests. Try a stretch, work together, or leave a mission for another day. A parent can read the clues aloud.</p><div className="segmented">{BOYS.map(n=><button key={n} className={boy===n?'selected':''} onClick={()=>setBoy(n)}>{n} · {n==='Nate'?'5':'8'}</button>)}</div><div className="segmented"><button className={scope==='daily'?'selected':''} onClick={()=>setScope('daily')}>Daily missions</button><button className={scope==='overall'?'selected':''} onClick={()=>setScope('overall')}>Whole-trip quests</button></div>{scope==='daily'&&<label>Day<select value={date} onChange={e=>setDate(e.target.value)}>{state.days.map(d=><option key={d.date} value={d.date}>{dayLabel(d.date)} · {d.title}</option>)}</select></label>}<div className="quest-progress"><strong>{done} / {list.length} explored</strong><progress max={Math.max(list.length,1)} value={done}/><span>{done===list.length&&done>0?'All these missions completed!':'Collect discoveries at your own pace.'}</span></div>
 <div className="feature-grid">{list.map(c=><article className={`feature-card quest ${c.completions[boy]?'finished':''}`} key={`${c.id}-${boy}`}><span className="eyebrow">{c.day?'DAILY MISSION':'TRIP QUEST'}</span><h2>{c.title}</h2><p>{c.notes}</p>{c.completions[boy]&&<small>Completed {dayLabel(japanDate(new Date(c.completions[boy])))} · {japanClock(new Date(c.completions[boy]))} JST</small>}<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate({type:'challengeStatus',id:c.id,person:boy,done:true,response:f.get('response')});}}><label>My discovery<textarea name="response" maxLength={2000} defaultValue={c.responses?.[boy]||''} placeholder="Tell a parent, type a note, or record your answer here" disabled={!parent&&user.name!==boy}/></label><div className="row wrap"><button className="primary" disabled={busy||(!parent&&user.name!==boy)}>{c.completions[boy]?'Save my discovery':'I did it!'}</button>{c.completions[boy]&&<button type="button" disabled={busy||(!parent&&user.name!==boy)} onClick={()=>mutate({type:'challengeStatus',id:c.id,person:boy,done:false})}>Undo</button>}{parent&&<button type="button" onClick={()=>setEdit(c)}>Edit mission</button>}</div></form></article>)}</div>{!list.length&&<p>No missions here yet. Add your own idea.</p>}
 {parent&&<><button className="button" onClick={()=>setEdit({day:scope==='daily'?date:null,participants:[boy],title:'',notes:''})}>Add a challenge</button>{edit&&<form className="feature-card" key={edit.id||'new'} onSubmit={save}><h2>{edit.id?'Edit challenge':'New challenge'}</h2><label>Title<input name="title" required maxLength={250} defaultValue={edit.title}/></label><label>Clues / stretch task<textarea name="notes" maxLength={2000} defaultValue={edit.notes}/></label><label>When<select name="day" defaultValue={edit.day||''}><option value="">Whole-trip quest</option>{state.days.map(d=><option key={d.date} value={d.date}>{dayLabel(d.date)}</option>)}</select></label><fieldset><legend>Explorers</legend>{BOYS.map(n=><label className="checkline" key={n}><input type="checkbox" name="participants" value={n} defaultChecked={edit.participants.includes(n)}/>{n}</label>)}</fieldset><div className="row wrap"><button className="primary" disabled={busy}>Save challenge</button><button type="button" onClick={()=>setEdit(null)}>Cancel</button>{edit.id&&<button type="button" className="danger" onClick={async()=>{if(confirm('Remove this challenge and its progress?')&&await mutate({type:'challengeRemove',id:edit.id}))setEdit(null);}}>Remove</button>}</div></form>}</>}
 </>;
}
export function Shopping({state,user,day,mutate,busy,initialId}){
 const initial=state.shopping.find(s=>s.id===initialId);
 const [query,setQuery]=useState(initial?.title||''),[person,setPerson]=useState(''),[date,setDate]=useState(''),[status,setStatus]=useState(initial?'all':'needed'),[edit,setEdit]=useState(null);
 const parent=user.role==='parent',items=state.shopping.filter(s=>(!person||s.person===person)&&(!date||s.day===date)&&(status==='all'||(status==='bought'?!!s.boughtAt:!s.boughtAt))&&[s.title,s.store,s.notes].join(' ').toLowerCase().includes(query.toLowerCase()));
 async function save(e){e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({type:edit.id?'shoppingEdit':'shoppingAdd',id:edit.id,title:f.get('title'),person:f.get('person'),day:f.get('day')||null,quantity:Number(f.get('quantity')),budget:f.get('budget')===''?null:Number(f.get('budget')),store:f.get('store'),url:f.get('url'),notes:f.get('notes')}))setEdit(null);}
 return <><p className="eyebrow">GOOD FINDS, USEFUL THINGS</p><h1>Shopping list</h1><p>Souvenirs, gifts, snacks and things we need. Tick off purchases so the family can see what is still needed.</p><button className="primary" onClick={()=>setEdit({person:user.name,day:null,quantity:1})}>Add an item</button><div className="document-filters"><label>Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Item, shop or note"/></label><div className="form-row"><label>For<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Everyone</option>{['Family',...state.members].map(n=><option key={n}>{n}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="needed">Still needed</option><option value="bought">Bought</option><option value="all">Everything</option></select></label><label>Day<DaySelect state={state} value={date} onChange={e=>setDate(e.target.value)} allowAll/></label></div></div><p><strong>{items.length} items</strong> · listed budgets ¥{items.reduce((sum,s)=>sum+(s.budget||0),0).toLocaleString()} <small>Budget is the total for each item, including its quantity.</small></p><div className="feature-grid">{items.map(s=><article className={`feature-card ${s.boughtAt?'finished':''}`} key={s.id}><div className="section-heading"><h2>{s.title}</h2><input aria-label={`Mark ${s.title} bought`} type="checkbox" checked={!!s.boughtAt} disabled={busy} onChange={e=>mutate({type:'shoppingStatus',id:s.id,done:e.target.checked})}/></div><p>{s.quantity} × · {s.person}{s.budget!==null&&` · Budget ¥${s.budget.toLocaleString()}`}</p><small>{s.day?dayLabel(s.day):'Any day'}</small><p>{s.store}</p><p>{s.notes}</p>{s.boughtAt&&<small>Bought by {s.boughtBy} · {japanClock(new Date(s.boughtAt))} JST</small>}<div className="row wrap">{s.store&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.store+' Japan')}`}>Find shop</a>}{s.url&&<a href={s.url} target="_blank" rel="noreferrer">Website</a>}{parent&&<><button onClick={()=>setEdit(s)}>Edit</button><button className="danger" onClick={()=>{if(confirm('Remove this shopping item?'))mutate({type:'shoppingRemove',id:s.id});}}>Remove</button></>}</div></article>)}</div>{!items.length&&<div className="empty">Nothing on this list yet.</div>}
 {edit&&<form key={edit.id||'new'} className="feature-card" onSubmit={save}><h2>{edit.id?'Edit item':'Add to the list'}</h2><label>Item<input name="title" required maxLength={250} defaultValue={edit.title||''}/></label><div className="form-row"><label>For<select name="person" defaultValue={edit.person}>{['Family',...state.members].map(n=><option key={n}>{n}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="1" max="999" defaultValue={edit.quantity}/></label><label>Total budget (yen)<input name="budget" type="number" min="0" max="10000000" step="1" defaultValue={edit.budget??''}/></label></div><label>Day<select name="day" defaultValue={edit.day||''}><option value="">Any day</option>{state.days.map(d=><option key={d.date} value={d.date}>{dayLabel(d.date)}</option>)}</select></label><label>Shop / area<input name="store" maxLength={2000} defaultValue={edit.store||''}/></label><label>Website<input name="url" type="url" maxLength={2000} placeholder="https://…" defaultValue={edit.url||''}/></label><label>Notes<textarea name="notes" maxLength={2000} placeholder="Size, colour, who it is for, or where we saw it" defaultValue={edit.notes||''}/></label><div className="row"><button className="primary" disabled={busy}>Save item</button><button type="button" onClick={()=>setEdit(null)}>Cancel</button></div></form>}
 </>;
}
