import React,{useRef,useState} from 'react';
import {Check,LockKeyhole,GripVertical,ArrowUp,ArrowDown,Plus,Trash2,Inbox} from 'lucide-react';
export default function DayTimeline({steps,current,today,parent,busy,selectStep,mutate,addStep,removeStep,optionStep}){
 const drag=useRef(null),[target,setTarget]=useState(null);
 const move=(id,to)=>{const ids=steps.map(s=>s.id),from=ids.indexOf(id);if(from<0||to<0||to>=ids.length||to===from)return;ids.splice(from,1);ids.splice(to,0,id);mutate({type:'reorder',day:today.date,ids});};
 // A stop is remembered as "between those two" — the coffee before the train, the walk we
 // forgot. So the gap itself is the button, and the form opens already knowing where the stop
 // goes, rather than adding it to the end of the day and leaving it to be dragged back up.
 const insert=(before,label)=>parent&&addStep?<button type="button" className={`timeline-insert${before?'':' end'}`} disabled={busy} aria-label={label} onClick={()=>addStep(before)}><Plus size={15}/>{before?null:<span>Add a stop</span>}</button>:null;
 // A stop can be added here, so it can be taken off here — the alternative was opening the whole
 // edit form to find the one button that deletes it. Nothing goes on the tap itself: it asks
 // first, because this is the one change to the day that cannot simply be made again.
 const drop=s=>parent&&removeStep?<button type="button" className="remove-stop" disabled={busy} aria-label={`Remove ${s.title} from this day`} onClick={()=>removeStep(s)}><Trash2 size={15}/></button>:null;
 // Beside it, the thing the family actually means most of the time: not today, but not gone. It
 // is its own icon rather than a step inside the removal, so nobody has to reach for the bin to
 // find it — and it goes on the tap, because Options is where a stop waits, not where it ends.
 const park=s=>parent&&optionStep?<button type="button" className="to-options" disabled={busy} aria-label={`Save ${s.title} to Options`} onClick={()=>optionStep(s)}><Inbox size={15}/></button>:null;
 return <aside className="timeline"><div className="section-heading"><h2>The day at a glance</h2><span>{today?.city}</span></div>{parent&&<p className="timeline-help">Drag a handle or use the arrows to reorder. Target and booking times stay the same. Tap a gap to add a stop where it belongs, the tray to move one to Options for another day, or the bin to take it off for good — the bin asks first.</p>}{steps.map((s,i)=><React.Fragment key={s.id}>{insert(s.id,`Add a stop before ${s.title}`)}<div data-step-id={s.id} className={`timeline-row ${target===s.id?'drop-target':''}`}><button className={`timeline-step ${s.id===current?.id?'active':''} ${s.status}`} onClick={()=>selectStep(s)}><span className="timeline-time">{s.time||'—'}</span><span className="timeline-dot">{s.status==='done'?<Check size={13}/>:s.locked?<LockKeyhole size={10}/>:null}</span><span><strong>{s.title}</strong><small>{s.status==='done'?'Completed':s.status==='skipped'?'Skipped':s.locked?'Fixed time':'Flexible'}</small></span></button>{parent&&<div className="reorder-tools"><button className="drag-handle" disabled={busy} aria-label={`Drag ${s.title} to reorder`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:s.id,target:s.id};setTarget(s.id);}} onPointerMove={e=>{if(!drag.current)return;const row=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-step-id]');if(row){drag.current.target=row.dataset.stepId;setTarget(row.dataset.stepId);}if(e.clientY<100)window.scrollBy(0,-16);if(e.clientY>window.innerHeight-100)window.scrollBy(0,16);}} onPointerUp={()=>{if(drag.current)move(drag.current.id,steps.findIndex(x=>x.id===drag.current.target));drag.current=null;setTarget(null);}} onPointerCancel={()=>{drag.current=null;setTarget(null);}}><GripVertical size={18}/></button><button disabled={busy||i===0} aria-label={`Move ${s.title} up`} onClick={()=>move(s.id,i-1)}><ArrowUp size={14}/></button><button disabled={busy||i===steps.length-1} aria-label={`Move ${s.title} down`} onClick={()=>move(s.id,i+1)}><ArrowDown size={14}/></button>{park(s)}{drop(s)}</div>}</div></React.Fragment>)}{insert(null,steps.length?'Add a stop at the end of the day':'Add the first stop of this day')}</aside>;
}
