// What you are likely to hear back. Saying a phrase is half of it; the other half is the answer,
// which comes quickly and is the part nobody practised. These are the two or three replies that
// actually come back most often, in the same sound-it-out spelling as the phrasebook (です →
// "dess", ます → "mass", ました → "mash-ta"), so they can be recognised rather than translated.
// A "…" stands for the part that changes — a number, a place, a time.
const r=(ja,say,en)=>({ja,say,en});
export const REPLIES={
 morning:[r('おはようございます','oh-ha-yoh go-zye-mass','Good morning (said straight back)'),r('いらっしゃいませ','ee-rash-shy-ma-seh','Welcome — what every shop and restaurant says as you walk in. No answer needed')],
 hello:[r('こんにちは','kon-nee-chee-wa','Hello (said straight back)'),r('いらっしゃいませ','ee-rash-shy-ma-seh','Welcome — the shop greeting. A nod is answer enough')],
 evening:[r('こんばんは','kon-ban-wa','Good evening (said straight back)'),r('いらっしゃいませ','ee-rash-shy-ma-seh','Welcome — the shop greeting. A nod is answer enough')],
 thanks:[r('どういたしまして','doh ee-ta-shee-mash-teh','You are welcome'),r('いいえ','ee-eh','Not at all — here it means “no need”, not “no”'),r('ありがとうございました','a-ree-ga-toh go-zye-mash-ta','Thank you — staff thanking you back for coming')],
 excuse:[r('はい','hye','Yes? — I am listening, go ahead'),r('少々お待ちください','shoh-shoh oh-ma-chee koo-da-sigh','One moment, please'),r('はい、どうぞ','hye, doh-zo','Yes, go ahead / after you')],
 sorry:[r('大丈夫ですよ','dye-joh-boo dess yo','It is all right'),r('いえいえ','ee-eh ee-eh','No, no — not at all'),r('気にしないでください','kee nee shee-nigh-deh koo-da-sigh','Please do not worry about it')],
 please:[r('かしこまりました','ka-shko-ma-ree-mash-ta','Certainly — the formal “understood”'),r('はい、どうぞ','hye, doh-zo','Here you are'),r('少々お待ちください','shoh-shoh oh-ma-chee koo-da-sigh','One moment, please')],
 yes:[r('かしこまりました','ka-shko-ma-ree-mash-ta','Certainly, understood'),r('では、こちらへどうぞ','deh-wa, ko-chee-ra eh doh-zo','Then this way, please'),r('ありがとうございます','a-ree-ga-toh go-zye-mass','Thank you')],
 no:[r('そうですか','soh dess ka','I see / is that so'),r('失礼しました','shee-tsoo-reh shee-mash-ta','Sorry to have troubled you')],
 fine:[r('かしこまりました','ka-shko-ma-ree-mash-ta','Understood — they will not offer again'),r('そうですか','soh dess ka','I see'),r('ありがとうございます','a-ree-ga-toh go-zye-mass','Thank you')],
 nicetomeet:[r('こちらこそ','ko-chee-ra ko-so','Likewise — the same to you'),r('よろしくお願いします','yo-ro-shee-koo oh-neh-guy shee-mass','Nice to meet you (said straight back)')],
 bye:[r('お気をつけて','oh-kee oh tsoo-keh-teh','Take care / safe travels'),r('またお越しください','ma-ta oh-ko-shee koo-da-sigh','Please come again'),r('ありがとうございました','a-ree-ga-toh go-zye-mash-ta','Thank you for coming')],
 itadakimasu:[r('どうぞ','doh-zo','Please, go ahead'),r('ごゆっくりどうぞ','go-yook-koo-ree doh-zo','Take your time and enjoy it')],
 gochisou:[r('ありがとうございました','a-ree-ga-toh go-zye-mash-ta','Thank you for coming'),r('またお越しください','ma-ta oh-ko-shee koo-da-sigh','Please come again'),r('お粗末さまでした','oh-so-ma-tsoo-sa-ma desh-ta','It was nothing much — a host being modest')],
 english:[r('少し','soo-ko-shee','A little — often more than a little'),r('すみません、できません','soo-mee-ma-sen, deh-kee-ma-sen','Sorry, I cannot'),r('ちょっとだけ','chot-to da-keh','Just a bit')],
 nojapanese:[r('大丈夫ですよ','dye-joh-boo dess yo','That is fine'),r('英語で大丈夫ですか？','ay-go deh dye-joh-boo dess ka','Is English all right?')],
 understand:[r('ちょっと待ってください','chot-to mat-teh koo-da-sigh','Wait a moment — usually while they find a phone or a pen'),r('こちらです','ko-chee-ra dess','It is this — they will point or show you'),r('大丈夫です','dye-joh-boo dess','It is fine, never mind')],
 again:[r('はい、もう一度','hye, moh ee-chee-do','Yes, once more'),r('ゆっくり言いますね','yook-koo-ree ee-mass neh','I will say it slowly')],
 slowly:[r('はい、わかりました','hye, wa-ka-ree-mash-ta','Yes, all right'),r('すみません','soo-mee-ma-sen','Sorry — then the same again, slower')],
 whatisthis:[r('これは…です','ko-reh wa … dess','This is …'),r('鶏肉です','toh-ree-nee-koo dess','It is chicken'),r('甘いです','a-my dess','It is sweet')],
 howmuch:[r('…円です','… en dess','It is … yen — watch the till screen'),r('税込みです','zay-ko-mee dess','Tax is included'),r('税抜きです','zay-noo-kee dess','Plus tax')],
 writeit:[r('はい、どうぞ','hye, doh-zo','Yes, here you are'),r('少々お待ちください','shoh-shoh oh-ma-chee koo-da-sigh','One moment, please')],
 wheretoilet:[r('あちらです','a-chee-ra dess','Over there — follow the hand'),r('まっすぐ行って右です','mas-soo-goo it-teh mee-gee dess','Straight on, then right'),r('二階です','nee-kai dess','On the second floor')],
 wherestation:[r('まっすぐです','mas-soo-goo dess','Straight ahead'),r('あの信号を左です','a-no shin-goh oh hee-da-ree dess','Left at those lights'),r('地下です','chee-ka dess','It is underground')],
 gohere:[r('ここですね','ko-ko dess neh','Here, right? — checking the map'),r('遠いですよ','toh-ee dess yo','It is a long way'),r('電車がいいです','den-sha ga ee dess','The train is best')],
 lost:[r('どちらへ？','do-chee-ra eh','Where are you going?'),r('地図を見せてください','chee-zoo oh mee-seh-teh koo-da-sigh','Show me the map, please'),r('一緒に行きましょう','ees-sho nee ee-kee-ma-shoh','Let us go together — it happens a lot')],
 near:[r('すぐそこです','soo-goo so-ko dess','It is just there'),r('近いです','chee-kigh dess','It is close'),r('ちょっと遠いです','chot-to toh-ee dess','It is a bit far — meaning quite far')],
 walk:[r('歩いて五分です','a-roo-ee-teh go-foon dess','Five minutes on foot'),r('行けますよ','ee-keh-mass yo','Yes, you can'),r('タクシーがいいです','tak-shee ga ee dess','A taxi would be better')],
 entrance:[r('あちらです','a-chee-ra dess','Over there'),r('反対側です','han-tai-ga-wa dess','On the other side'),r('裏です','oo-ra dess','Round the back')],
 lift:[r('あちらにあります','a-chee-ra nee a-ree-mass','There is one over there'),r('奥です','oh-koo dess','At the back'),r('ありません','a-ree-ma-sen','There is not one')],
 ticket:[r('券売機です','ken-bai-kee dess','At the ticket machine'),r('みどりの窓口です','mee-do-ree no ma-do-goo-chee dess','At the ticket office — the green sign'),r('あちらです','a-chee-ra dess','Over there')],
 doesitgo:[r('行きます','ee-kee-mass','Yes, it goes there'),r('行きません','ee-kee-ma-sen','No, it does not'),r('乗り換えです','no-ree-ka-eh dess','You need to change trains')],
 platform:[r('…番線です','… ban-sen dess','Platform …'),r('三番線です','san ban-sen dess','Platform three'),r('向かいのホームです','moo-kai no hoh-moo dess','The platform opposite')],
 nexttrain:[r('…時…分です','… jee … foon dess','At … o’clock and … minutes'),r('五分後です','go-foon go dess','In five minutes'),r('もう終わりました','moh oh-wa-ree-mash-ta','It has finished for the day')],
 iccard:[r('使えます','tsoo-ka-eh-mass','Yes, you can'),r('使えません','tsoo-ka-eh-ma-sen','No, you cannot'),r('現金のみです','gen-keen no-mee dess','Cash only')],
 taxi:[r('かしこまりました','ka-shko-ma-ree-mash-ta','Certainly'),r('シートベルトをお願いします','shee-toh be-roo-toh oh oh-neh-guy shee-mass','Seatbelts, please'),r('着きました','tsoo-kee-mash-ta','We are here')],
 thisone:[r('かしこまりました','ka-shko-ma-ree-mash-ta','Certainly'),r('温めますか？','a-ta-ta-meh-mass ka','Shall I heat it up? — at a convenience store'),r('お箸はおつけしますか？','oh-ha-shee wa oh-tsoo-keh shee-mass ka','Would you like chopsticks?')],
 justlooking:[r('ごゆっくりどうぞ','go-yook-koo-ree doh-zo','Take your time'),r('どうぞ','doh-zo','Please do')],
 card:[r('はい、使えます','hye, tsoo-ka-eh-mass','Yes, you can'),r('現金のみです','gen-keen no-mee dess','Cash only'),r('一括でよろしいですか？','eek-ka-tsoo deh yo-ro-shee dess ka','In one payment? — just say “hye”')],
 bag:[r('袋は有料です','foo-koo-ro wa yoo-ryoh dess','Bags cost a few yen'),r('お分けしますか？','oh-wa-keh shee-mass ka','Shall I bag them separately?'),r('このままでよろしいですか？','ko-no ma-ma deh yo-ro-shee dess ka','Is it all right as it is, with just a sticker?')],
 taxfree:[r('パスポートをお願いします','pa-soo-poh-toh oh oh-neh-guy shee-mass','Your passport, please'),r('五千円以上です','go-sen en ee-joh dess','It has to be five thousand yen or more'),r('免税カウンターへどうぞ','men-zay kown-tah eh doh-zo','Please go to the tax-free counter')],
 tryon:[r('どうぞ','doh-zo','Go ahead'),r('試着室はこちらです','shee-cha-koo-shee-tsoo wa ko-chee-ra dess','The fitting room is this way'),r('何点ですか？','nan-ten dess ka','How many items?')],
 highchair:[r('ございます','go-zai-mass','Yes, we have'),r('少々お待ちください','shoh-shoh oh-ma-chee koo-da-sigh','One moment, please'),r('ございません','go-zai-ma-sen','No, we do not')],
 childfree:[r('…歳以下は無料です','… sai ee-ka wa moo-ryoh dess','Free for … and under'),r('何歳ですか？','nan-sai dess ka','How old are they?'),r('子供料金です','ko-do-mo ryoh-keen dess','It is the child’s price')],
 nappy:[r('多目的トイレにあります','ta-mo-koo-teh-kee toy-reh nee a-ree-mass','In the accessible toilet'),r('ベビールームはあちらです','beh-bee roo-moo wa a-chee-ra dess','The baby room is over there')],
 maigo:[r('お名前は？','oh-na-ma-eh wa','What is their name?'),r('何歳ですか？','nan-sai dess ka','How old are they?'),r('放送します','hoh-soh shee-mass','We will make an announcement')],
 twoadults:[r('四名様ですね','yon-may-sa-ma dess neh','Four of you, yes?'),r('こちらへどうぞ','ko-chee-ra eh doh-zo','This way, please'),r('少々お待ちください','shoh-shoh oh-ma-chee koo-da-sigh','Please wait a moment — there is a queue')],
 help:[r('どうしましたか？','doh shee-mash-ta ka','What happened?'),r('大丈夫ですか？','dye-joh-boo dess ka','Are you all right?')],
 hospital:[r('救急車を呼びましょうか？','kyoo-kyoo-sha oh yo-bee-ma-shoh ka','Shall I call an ambulance?'),r('タクシーで行けます','tak-shee deh ee-keh-mass','You can go by taxi'),r('近くにあります','chee-ka-koo nee a-ree-mass','There is one nearby')],
 ambulance:[r('火事ですか、救急ですか？','ka-jee dess ka, kyoo-kyoo dess ka','Fire or ambulance? — the first question on 119'),r('住所を教えてください','joo-sho oh oh-shee-eh-teh koo-da-sigh','Tell me the address'),r('呼びます','yo-bee-mass','I will call')],
 police:[r('どうしましたか？','doh shee-mash-ta ka','What happened?'),r('交番はあちらです','koh-ban wa a-chee-ra dess','The police box is over there'),r('呼びます','yo-bee-mass','I will call')],
 allergy:[r('何のアレルギーですか？','nan no a-reh-roo-gee dess ka','Allergic to what?'),r('確認します','ka-koo-neen shee-mass','I will check — with the kitchen'),r('入っています','hait-teh ee-mass','It contains it — this is the one to listen for'),r('入っていません','hait-teh ee-ma-sen','It does not contain it')],
 lostitem:[r('どこでなくしましたか？','do-ko deh na-koo-shee-mash-ta ka','Where did you lose it?'),r('どんな鞄ですか？','don-na ka-ban dess ka','What kind of bag?'),r('届いています','to-doy-teh ee-mass','It has been handed in')]
};
export const repliesFor=phrase=>REPLIES[phrase?.id]||[];
